### ISSUE TITLE
Issue in File Upload field when upload file without extension

### ISSUE THREAD

**Issue by giordanop** [umbraco/Umbraco.Forms.Issues#1020]
When clicking the "Submit" button in a form where a file without an extension has been uploaded to a File Upload field, the form encounters an error and crashes.

Reproduction
------------

### Bug summary
It seems there is an issue in the FileUpload class in Umbraco.Forms.Core.Providers.FieldTypes namespace. I suspect the error is related to the line `file.FileName.Substring(path.LastIndexOf("."))`

### Stack trace
```
System.ArgumentOutOfRangeException: StartIndex cannot be less than zero.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Umbraco.Forms.Core.Providers.FieldTypes.FileUpload.ValidateField(Form form, Field field, IEnumerable`1 postedValues, HttpContextBase context, IFormStorage formStorage)
   at Umbraco.Forms.Web.Controllers.UmbracoFormsController.ValidateFormState(FormViewModel model, Form form, HttpContextBase context)
   at Umbraco.Forms.Web.Controllers.UmbracoFormsController.HandleForm(FormViewModel model)
   at lambda_method(Closure , ControllerBase , Object[] )
```

### Specifics
Umbraco CMS 8.18.7
Umbraco Forms 8.13.2

### Steps to reproduce

1. Create a new form containing a File Upload field. When adding the File Upload field, on field "Predefined allowed file types:" choose one or more extensions (e.g. PDF).
2. Create a new page and add the form to the page, publish it
3. Open the page in the website and upload a file without extension to the File Upload field
4. Click Submit button

### Expected result

When the submit button is clicked, validation fails, as a consequence a validation error message is rendered in the web page. 

### Actual result

The form page crashes.

**Comment by AndyButland** [comment]
Thanks for reporting @giordanop.  We have a fix for this now which will be available in the next round of patch releases.
