### ISSUE TITLE
Invalid column name 'NodeId' after an upgrade (restart fixes)

### ISSUE THREAD

**Issue by Myster** [umbraco/Umbraco.Forms.Issues#1176]
### Bug summary
This issue only occurred immediately after upgrading  Umbraco 10 to 13, and forms from 10.4.0 to 13.0.2
Then click a form in the back office to view it, a red bar shows at the bottom indicating an exception occurred. 
Restarting the application resolves this issue.

### Reproduction & Summary

An existing site with existing forms on these versions
```
    <PackageReference Include="Umbraco.Cms" Version="10.8.2" />
    <PackageReference Include="Umbraco.Forms" Version="10.4.0" />
```
Was upgraded to:
```
    <PackageReference Include="Umbraco.Cms" Version="13.1.1" />
    <PackageReference Include="Umbraco.Forms" Version="13.0.2" />
```
After the upgrade when visiting a form in the back office this exception occurs:
```
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'NodeId'.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 204
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)
   at NPoco.Database.ExecuteDataReader(DbCommand cmd, Boolean sync)
   at NPoco.AsyncHelper.RunSync[T](Task`1 task)
   at NPoco.Database.QueryImp[T](T instance, Expression`1 listExpression, Func`2 idFunc, Sql Sql, PocoData pocoData)+MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at NPoco.Database.FirstOrDefault[T](Sql sql)
   at Umbraco.Forms.Core.Persistence.Repositories.Implement.FormRepository.PerformGet(Guid id)
   at Umbraco.Cms.Core.Cache.NoCacheRepositoryCachePolicy`2.Get(TId id, Func`2 performGet, Func`2 performGetAll)
   at Umbraco.Forms.Core.Services.BaseService`3.Get(Guid id)
   at Umbraco.Forms.Web.Editors.FormController.GetWithWorkflowsByGuid(Guid guid, Boolean applyDictionaryTranslations)
   at lambda_method8747(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
ClientConnectionId:9c0d9deb-1312-4e21-8460-500020215d53
Error Number:207,State:1,Class:16

```

**Comment by AndyButland** [comment]
Obviously it's tricky to to fully replicate an upgrade scenario, but I tried to follow the path you took and didn't find a problem.  Here's what I did:

```
dotnet new install Umbraco.Templates::10.8.2
dotnet new umbraco --name TestProject
cd .\TestProject\
dotnet add package Umbraco.Forms --version 10.4.0
dotnet run
```

Then clicked through the installer and used a SQL Server database.
Created a form.
Stopped site, and upgraded to the versions you have have indicated.
 - Updated `<TargetFramework>` to `net8.0`
 - Updated pacreferences

``` 
dotnet build
dotnet run
```

Got "website under maintenance" screen.

Navigated to `/install`, logged in, ran upgrade.  Could see in the logs that the Forms upgrade ran, and then opening and re-saving the form worked as expected.
Navigated to https://localhost:44352/install, logged in, ran upgrade

I'll close this given there doesn't seem to be a general problem and you've resolved your issue after a restart - but if you have any further to add or can see something different between the upgrade I've followed and yours, please feel free to re-open.

**Comment by Andrei-** [comment]
I'm getting exactly the same issue after upgrading umbraco from v10.8.5 -> v13.4.0 and umbraco forms from 10.8.2 -> [13.0.1 or 13.2.1]
It's an unattended upgrade - umbraco and various packages are migrated properly except for umbraco forms which is only migrated after a second restart. 
In the console log I can see that Forms determines that 'need to execute migrations', but it doesn't do it. A new restart however triggers the forms migration and seems to fix it.

**Comment by Wiggee11** [comment]
There is definitely an issue here with the Umbraco Forms migrations not runing during an upgrade from 10 -> 13.

When trying to upgrade Umbraco CMS 10.8.6 -> 13.4.1 and Umbraco Forms 10.3.1 -> 13.1.2 I got the same `Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'NodeId'.` error.

Found this issue and on inspecting the logs, the Umbraco Forms migrations did not run.

| key	| value |
|---|---|
| Umbraco.Core.Upgrader.State+Umbraco.Core | {985AF2BA-69D3-4DBA-95E0-AD3FA7459FA7} |
| Umbraco.Core.Upgrader.State+UmbracoForms | 5d84fee1-388c-4e5f-b98c-1e66947278f1 |

Comparing to another application using Umbraco 13 and Forms 13.1.2, the expected migration key is:
| key	| value |
|---|---|
| Umbraco.Core.Upgrader.State+UmbracoForms | 773ae769-00b7-4429-b7d5-de0fda0b4217 |

After restarting the application, the Umbraco Forms migration runs:
```
Unattended upgrade completed for UmbracoForms (310ms) [Timing 312d8c4]
Done
At 773ae769-00b7-4429-b7d5-de0fda0b4217
Execute EnsureKeyForRelationTypeBetweenContentAndForms
At 44949e12-e4ef-42c0-949b-67286b946fe0
Execute AddRedirectToPageIdToMacro
At 6f0eb771-6690-4b53-870a-f7dbb2785cac
Execute PopulateNodeTableAndNodeIdToForms
At e0290a40-91c9-4acb-a7ca-d312037078f2
SQL [0]: ALTER TABLE [UFForms] ADD [NodeId] INTEGER NULL
Execute AddFormNodeIdColumn
At c3e657f6-3ae7-4ee9-b442-01702a41de9a
Execute AddRelationTypeBetweenContentAndForms
At 22df962a-ae26-4bdd-b8fd-0513a9c636bf
CREATE NONCLUSTERED INDEX [IX_UFForms_FolderKey] ON [UFForms] ([FolderKey])
Execute EnsureIndexOnFormFolderKey
At 5d84fee1-388c-4e5f-b98c-1e66947278f1
Starting 'UmbracoForms'...
```

KeyValue table migration now correct:
| key	| value |
|---|---|
| Umbraco.Core.Upgrader.State+UmbracoForms | 773ae769-00b7-4429-b7d5-de0fda0b4217 |

Suggest you repoen this issue @AndyButland and investigate.

Full error log:
```
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'NodeId'.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 204
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass35_0.<ExecuteDbDataReader>b__0()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass38_0`1.<Execute>b__0()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f)
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at NPoco.Database.<>c__DisplayClass298_0.<ExecuteReaderHelper>b__0()
   at NPoco.Database.ExecutionHook[T](Func`1 action)
   at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)
   at NPoco.Database.ExecuteDataReader(DbCommand cmd, Boolean sync)
   at NPoco.AsyncHelper.RunSync[T](Task`1 task)
   at NPoco.Database.QueryImp[T](T instance, Expression`1 listExpression, Func`2 idFunc, Sql Sql, PocoData pocoData)+MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at NPoco.Database.FirstOrDefault[T](Sql sql)
   at Umbraco.Forms.Core.Persistence.Repositories.Implement.FormRepository.PerformGet(Guid id)
   at Umbraco.Cms.Core.Cache.NoCacheRepositoryCachePolicy`2.Get(TId id, Func`2 performGet, Func`2 performGetAll)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.EntityRepositoryBase`2.Get(TId id)
   at Umbraco.Forms.Core.Services.BaseService`3.Get(Guid id)
   at Umbraco.Forms.Web.Services.FormRenderingService.GetForm(Guid formId)
   at Umbraco.Forms.Web.Services.FormRenderingService.GetFormModelAsync(HttpContext httpContext, Guid formId, Nullable`1 recordId, String theme)
   at Umbraco.Forms.Web.ViewComponents.RenderFormViewComponent.InvokeAsync(Guid formId, Nullable`1 recordId, String theme, Boolean includeScripts, Nullable`1 redirectToPageId)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsyncCore(ObjectMethodExecutor executor, Object component, ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsync(ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsync(ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper.InvokeCoreAsync(ViewComponentDescriptor descriptor, Object arguments)
   at AspNetCoreGeneratedDocument.Views_MacroPartials_InsertUmbracoFormWithTheme.ExecuteAsync()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.ViewViewComponentResult.ExecuteAsync(ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.ViewViewComponentResult.Execute(ViewComponentContext context)
   at Umbraco.Cms.Web.Common.Macros.PartialViewMacroEngine.Execute(MacroModel macro, IPublishedContent content)
   at Umbraco.Cms.Web.Common.Macros.MacroRenderer.<>c__DisplayClass26_0.<ExecuteMacroOfType>b__0()
   at Umbraco.Cms.Web.Common.Macros.MacroRenderer.ExecuteProfileMacroWithErrorWrapper(MacroModel macro, String msgIn, Func`1 getMacroContent, Func`1 msgErr)
   at Umbraco.Cms.Web.Common.Macros.MacroRenderer.ExecuteMacroWithErrorWrapper(MacroModel macro, String msgIn, String msgOut, Func`1 getMacroContent, Func`1 msgErr)
   at Umbraco.Cms.Web.Common.Macros.MacroRenderer.ExecuteMacroOfType(MacroModel model, IPublishedContent content)
   at Umbraco.Cms.Web.Common.Macros.MacroRenderer.RenderAsync(MacroModel macro, IPublishedContent content)
   at Umbraco.Cms.Web.Common.Macros.MacroRenderer.RenderAsync(String macroAlias, IPublishedContent content, IDictionary`2 macroParams)
   at Umbraco.Cms.Core.Templates.UmbracoComponentRenderer.RenderMacroAsync(IPublishedContent content, String alias, IDictionary`2 parameters)
   at Umbraco.Cms.Core.Templates.UmbracoComponentRenderer.RenderMacroAsync(Int32 contentId, String alias, IDictionary`2 parameters)
   at Umbraco.Cms.Web.Common.UmbracoHelper.RenderMacroAsync(String alias, IDictionary`2 parameters)
   at AspNetCore.Views_Partials_grid_editors_macro.ExecuteAsync() in \Views\Partials\grid\editors\macro.cshtml:line 14
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.RenderPartialCoreAsync(String partialViewName, Object model, ViewDataDictionary viewData, TextWriter writer)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.PartialAsync(String partialViewName, Object model, ViewDataDictionary viewData)
   at AspNetCore.Views_Partials_grid_editors_base.ExecuteAsync() in \Views\Partials\grid\editors\base.cshtml:line 6
ClientConnectionId:8cbf9cd7-339b-41d9-ab8f-d82036cf00d3
Error Number:207,State:1,Class:16
```

**Comment by Wiggee11** [comment]
Will this be reopened @AndyButland ?

**Comment by AndyButland** [comment]
I've had another look at it today @Wiggee11 . Repeating the [steps I tried before](https://github.com/umbraco/Umbraco.Forms.Issues/issues/1176#issuecomment-1973064261) yields the same result, but I do see the problem when I enable unattended migrations.  As you've found - the CMS updates itself, but it needs a restart for Forms to do so too.

I won't re-open this as I believe this is an issue with the CMS rather than Forms, and so would be the same for any packages that require database migrations and are updated unattended at the same time as the CMS.

I haven't dug too far but I think I can see there'll be an issue from here...

https://github.com/umbraco/Umbraco-CMS/blob/dfe41d7f7630b5d1be144a4ea1fd8e861143f839/src/Umbraco.Infrastructure/Runtime/RuntimeState.cs#L208

... where it's determined if unattended upgrades are necessary, which will first detect the CMS itself needs update.

And then here...

https://github.com/umbraco/Umbraco-CMS/blob/9a49ab712b0f244c3e6522ecf654c072eaacba7b/src/Umbraco.Infrastructure/Install/UnattendedUpgrader.cs#L45

... where the detected upgrade task is carried out.

You can see it only does a CMS migration or a package migration, not both.  On the restart, the CMS is already updated and so the package migration flow is executed.

You are welcome to create an issue on the [CMS tracker](https://github.com/umbraco/Umbraco-CMS/issues) for this (I suggest you do, such that you'll get notifications, rather than me doing it myself).

If you include a link to this comment - or copy the relevant detail - that would be useful.

Finally I'll just include [a link here to the Forms migrations](https://github.com/umbraco/Forms/blob/v13/dev/src/Umbraco.Forms.Core/Migrations/FormsMigrationPlan.cs).  You won't be able to see that as it's closed source, but it might help anyone at HQ that looks into the issue - just in case we are doing anything "wrong" with the package migration in Forms.  I don't believe so though, as it's just using the standard `PackageMigrationPlan` technique.
