### ISSUE TITLE
Getting Error On Umbraco Forms while i am not using any type of controller and RenderingForm from @Umbraco.RenderMacro in 8.18.9 Version

### ISSUE THREAD

**Issue by MalikFarhanManzoor** [umbraco/Umbraco.Forms.Issues#1184]
System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'UFForms'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 208
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass30_0.<ExecuteDbDataReader>b__0() in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 204
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass33_0`1.<Execute>b__0() in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 222
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryPolicy.cs:line 172
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 219
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 204
   at System.Data.Common.DbCommand.ExecuteReader()
   at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)
   at NPoco.Database.ExecuteDataReader(DbCommand cmd)
   at NPoco.Database.<QueryImp>d__164`1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at NPoco.Database.FirstOrDefault[T](Sql sql)
   at Umbraco.Forms.Core.Persistence.Repositories.Implement.FormRepository.PerformGet(Guid id)
   at Umbraco.Core.Cache.NoCacheRepositoryCachePolicy`2.Get(TId id, Func`2 performGet, Func`2 performGetAll) in D:\a\1\s\src\Umbraco.Core\Cache\NoCacheRepositoryCachePolicy.cs:line 17
ClientConnectionId:XXX
Error Number:208,State:1,Class:16

**Comment by MalikFarhanManzoor** [comment]
![Capture](https://github.com/umbraco/Umbraco.Forms.Issues/assets/160225264/cb4f649a-324d-49ff-8ad1-4c9c7dead690)

**Comment by MalikFarhanManzoor** [comment]
Is it all ok There and StoreUmbracoFormsInDb key in the <settings> section its Also the "True"

**Comment by AndyButland** [comment]
Then if you restart your site now you should find migrations will run to create the necessary tables in your database (including `UFForms` that you had missing before).

**Comment by MalikFarhanManzoor** [comment]
How can i restart my site from IIS?

**Comment by MalikFarhanManzoor** [comment]
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/160225264/6203fdd5-aad2-47b1-a3dd-a0187baad7dd)

thankss i Get it

**Comment by MalikFarhanManzoor** [comment]
![image](https://github.com/umbraco/Umbraco.Forms.Issues/assets/160225264/9c74ad56-9ddc-47eb-af3b-ec2bc84fe6c4)

Thankss i Get it
