### ISSUE TITLE
7.1.0 Form with Upload Field Type Fails on Submit

### ISSUE THREAD

**Issue by paulsterling** [umbraco/Umbraco.Forms.Issues#122]
After the auto-update for Forms 7.0.6 > 7.1.0 all Forms with an Upload field type fail on Submit when no file is selected for the upload field with the below error. Selecting a file prior to submission or removing the Upload field allows the submission.

```
 2019-03-26 12:49:45,003 [P13796/D2/T14] ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Umbraco.Forms.Core.Providers.FieldTypes.FileUpload.ValidateField(Form form, Field field, IEnumerable`1 postedValues, HttpContextBase context)
   at Umbraco.Forms.Web.Controllers.UmbracoFormsController.ValidateFormState(FormViewModel model, Form form, HttpContextBase context, Boolean captchaIsValid)
   at Umbraco.Forms.Web.Controllers.UmbracoFormsController.HandleForm(FormViewModel model, Boolean captchaIsValid)
   at lambda_method(Closure , ControllerBase , Object[] )
...
```

**Comment by bergmania** [comment]
Thanks for reporting. That's clearly a bug :(

PR: 
- V7: https://github.com/umbraco/Forms/pull/264
- V8: https://github.com/umbraco/Forms/pull/263

**Comment by bergmania** [comment]
There is a nighly build with the fix available here
http://nightly.umbraco.org/?container=umbraco-forms-nightlies

Name `7.1.1-alpha-20190327-004` and `8.1.1-gamma.10103`.
