### ISSUE TITLE
Internal exception in entry count display handler, and number of entries is always zero

### ISSUE THREAD

**Issue by jsobell** [umbraco/Umbraco.Forms.Issues#1275]
A brief description of the issue goes here.

When using SQLite (and possibly other data sources) the code runs a SQL Count for the entries label, but attempts to cast it to an integer, but the returned value is a long integer

Reproduction
------------

Install Forms in any default project, show the Forms screen.

### Bug summary

The internal code performs a cast, in the format `var numrows = (int)ExecuteSql("Select count(*) from blah blah")`, but this return a 64 bit integer, not 32, so it can't be cast, causing the exception:

```
[21:06:49 ERR] An unhandled exception has occurred while executing the request.
System.InvalidCastException: Unable to cast object of type 'System.Int64' to type 'System.Int32'.
at Umbraco.Forms.Core.Searchers.FormRecordSearcher.QueryDataBaseForSubmissionsMetadata(Guid formId, RecordFilter model)
at Umbraco.Forms.Core.Searchers.FormRecordSearcher.QueryDataBaseForMetadata(Guid formId, RecordFilter filter)
at Umbraco.Forms.Web.Api.ManagementApi.Record.GetMetadataController.Retrieve(Guid formId, RecordFilter model)
at lambda_method593(Closure, Object, Object[])
```

### Specifics

This does not cause a fatal exception, but results in the screen always showing zero entries, and throws an internally caught exception.

### Expected result

No crash, and the number of entries to be displayed

**Comment by AndyButland** [comment]
Thanks for catching and reporting this @jsobell.  Looks like it is an issue with SQLite only as I wasn't seeing this testing with SQLServer.  I've fixed and it'll be released in the next patch.
