### ISSUE TITLE
Error cannot serialize an object of type 'Umbraco.Forms.Web.Models.FormViewModel' when submitting form

### ISSUE THREAD

**Issue by GianniDPC** [umbraco/Umbraco.Forms.Issues#1312]
A brief description of the issue goes here.

When I submit an umbraco form sometimes I get an error: cannot serialize an object of type 'Umbraco.Forms.Web.Models.FormViewModel' when submitting form. It seems to happen at random and I can't seem to pinpoint why it works sometimes and other times it doesn't. 

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

When I submit an umbraco form sometimes I get an error: cannot serialize an object of type 'Umbraco.Forms.Web.Models.FormViewModel' when submitting form. It seems to happen at random and I can't seem to pinpoint why it works sometimes and other times it doesn't. It seems like it puts an object of FormViewModel in TempData while it is recommended to first serialize the object which doesn't seem to happen here, which would be a potential solution.

```
Exception message: The 'Microsoft.AspNetCore.Mvc.ViewFeatures.Infrastructure.DefaultTempDataSerializer' cannot serialize an object of type 'Umbraco.Forms.Web.Models.FormViewModel'.
Exception info:
System.InvalidOperationException: The 'Microsoft.AspNetCore.Mvc.ViewFeatures.Infrastructure.DefaultTempDataSerializer' cannot serialize an object of type 'Umbraco.Forms.Web.Models.FormViewModel'.
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Infrastructure.DefaultTempDataSerializer.Serialize(IDictionary`2 values)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.CookieTempDataProvider.SaveTempData(HttpContext context, IDictionary`2 values)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.TempDataDictionary.Save()
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter.OnResultExecuted(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at DBS.Extensions.UmbracoApplicationBuilderExtensions.<>c__DisplayClass0_0.<<RedirectUserWithLanguage>b__0>d.MoveNext() in D:\a\1\s\website_umbraco\Extensions\UmbracoApplicationBuilderExtensions.cs:line 55
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.Common.Middleware.BasicAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.BackOffice.Middleware.BackOfficeExternalLoginProviderErrorMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at UrlTracker.Middleware.UrlTrackerRedirectMiddleware.InvokeAsync(HttpContext context)
   at UrlTracker.Middleware.UrlTrackerClientErrorTrackingMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext httpContext, Boolean retry)
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 121
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.Common.Middleware.PreviewAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Forms.Web.HttpModules.ProtectFormUploadRequestsMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at DBS.Middleware.UrlValidatorMiddleware.InvokeAsync(HttpContext context, IKrzLogger logger) in D:\a\1\s\website_umbraco\Middleware\UrlValidatorMiddleware.cs:line 27
   at DBS.Middleware.KrzRequestLogMiddleware.InvokeAsync(HttpContext context, IKrzLogger logger) in D:\a\1\s\website_umbraco\Middleware\KrzRequestLogMiddleware.cs:line 76
   at DBS.Middleware.ExceptionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\website_umbraco\Middleware\ExceptionMiddleware.cs:line 105
```

### Specifics

I have the issue on multiple sites:

With these umbraco forms versions
- 10.5.2
- 10.5.5

And these Umbraco versions:
- 10.7.0
- 10.8.5

### Steps to reproduce
Submit an umbraco form on a page.

### Expected result

It submits the form without throwing an exception.

### Actual result

See bug summary

**Comment by GianniDPC** [comment]
> Would certainly like to get to the bottom of this, but it's not something I've seen or heard reported before, so sounds like it will be difficult to replicate. Please do update if you are able to get further towards identifying when it occurs, perhaps for a specific form, or a form with certain settings.

The only thing I found was this post on the umbraco forums: https://our.umbraco.com/forum/using-umbraco-and-getting-started/113042-error-submitting-multi-page-umbraco-form

I'll try keep you posted if I can give you more detailed information.

**Comment by GianniDPC** [comment]
Hi @AndyButland I attached a working and failing example. This contains a serialized version of the FormViewModel. It seems to fail when StoreFormModel is called where the model is assigned to `tempData["umbracoformsform"]`

**Comment by GianniDPC** [comment]
Hi @AndyButland to give you some more specifics. I was able to always reproduce the issue when disabling client side validation and using the umbraco form in a custom umbraco controller (custom routing). This does not happen when using the form in a vanilla umbraco page. I know client side validation should be enabled for Umbraco Forms as it states in the documentation but the issue arose in Production, so it must be that some clients have the client side validation disabled maybe due to adblockers or something? Anyway I think it shouldn't crash either way.

**Comment by AndyButland** [comment]
Thanks for the further details @GianniDPC.  It does look like there's something amiss here, and could be we are doing something we should correct... but I'm afraid I'm still struggling to replicate.  Can I play back my test steps to you please and see if you can spot anything that might be materially different from your setup?

Steps:

- Created a multi-page form and added it via a form picker to an Umbraco document.
- Included a required field.
- Rendered using standard template, all seems to work (even when JavaScript disabled).
- Added a custom route rendering as per the code below.
- Again all seems to work OK.

Custom route:

```
using Microsoft.AspNetCore.Mvc.Filters;
using Umbraco.Cms.Core.Composing;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.Web;
using Umbraco.Cms.Web.Common.ApplicationBuilder;
using Umbraco.Forms.Testsite.Controllers;

namespace Umbraco.Forms.TestSite.Business
{
    public class MyCustomRouteComposer : IComposer
    {
        public void Compose(IUmbracoBuilder builder)
        {
            builder.Services.Configure<UmbracoPipelineOptions>(options =>
            {
                options.AddFilter(new UmbracoPipelineFilter(nameof(MyCustomRouteController))
                {
                    Endpoints = app => app.UseEndpoints(endpoints =>
                    {
                        endpoints.MapControllerRoute(
                            "My custom controller",
                            "/custom/{action}",
                            new { Controller = "MyCustomRoute", Action = "Index" })
                            .ForUmbracoPage(FindContent);
                    })
                });
            });
        }

        private IPublishedContent FindContent(ActionExecutingContext actionExecutingContext)
        {
            IUmbracoContextAccessor umbracoContextAccessor = actionExecutingContext.HttpContext.RequestServices
                .GetRequiredService<IUmbracoContextAccessor>();
            IUmbracoContext umbracoContext = umbracoContextAccessor.GetRequiredUmbracoContext();

            return umbracoContext?.Content?.GetById(3233) ?? throw new InvalidOperationException("Could not find content.");
        }
    }
}
```

Custom controller:

```
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Umbraco.Cms.Web.Common.Controllers;

namespace Umbraco.Forms.Testsite.Controllers
{
    public class MyCustomRouteController : UmbracoPageController
    {
        public MyCustomRouteController(ILogger<MyCustomRouteController> logger, ICompositeViewEngine compositeViewEngine)
            : base(logger, compositeViewEngine)
        {
        }

        public IActionResult Index()
        {
            return View("~/Views/SimpleForm.cshtml", CurrentPage);
        }
    }
}
```

Template:

```
@using Umbraco.Cms.Web.Common.PublishedModels;
@using Umbraco.Forms.Web;
@using Umbraco.Forms.Web.Extensions;
@using Umbraco.Cms.Core.Configuration.Models;

@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.SimpleForm>
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
	Layout = null;
}
<html>
<head>
<title>Simple Form Page</title>
</head>
<body>
<h1>Simple Form Page</h1>
@if (Model.Form.HasValue)
{
  @await Component.InvokeAsync("RenderForm", new { formId = Model.Form, theme = "default", includeScripts = true })
}

@Html.RenderUmbracoFormDependencies()

</body>
</html>

```

**Comment by GianniDPC** [comment]
Hi Andy,

After further debugging in our development environment, we discovered that the error is due to an issue in our code. The exception "Cannot serialize an object of type 'Umbraco.Forms.Web.Models.FormViewModel'" occurs because the Umbraco Form isn't being rendered on the page. However, to fully reproduce the issue, we still need to disable client-side validation.

Additionally, we found that the error on our side is linked to some strange behavior with the custom route. In your example, adding an additional URL segment (e.g., /product-8888) works when loading the page. But after submitting the form (again with validation scripts disabled), the URL segment fails to bind to my Index action, even though the custom route is set up correctly.

When inspecting the Request object, the URL looks correct, which makes the binding failure puzzling. Also, while the CurrentPage object is in the correct language, the Thread.CurrentCulture unexpectedly defaults to en-US. This mismatch triggered an exception in our code because it attempted to retrieve an Umbraco page URL using a language (en-US) that doesn't exist.

Let me know if you need further details or have any suggestions on how to resolve this.

**Comment by GianniDPC** [comment]
Hi Andy,

I digged a little deeper and found that RequestLocalizationMiddleware sets the CultureInfo. In the UmbracoPublishedContentCultureProvider the GetProviderCultureResult return null when posting the form (with failing validation and client side validation off) so it tries to return to the same page. But doing a GET request for the same page the GetProviderCultureResult returns an actual object.

**Comment by AndyButland** [comment]
Must admit you've lost me a little bit in your last two comments @GianniDPC - you've gone now more into issues with custom routing I believe, which if you've found something, would be a CMS issue.  But if you are able to provide the simplest possible steps to replicate (i.e. extending what I've shown above where I couldn't see an issue) we can look to take it further.

**Comment by GianniDPC** [comment]
@AndyButland I honestly don't know it it is a bug in the forms package or in the CMS it self. I attached an example. 
So the issues with it are:

- The form can't be posted using the second route (internal server error) when two routes are created going to the same action method (see Startup.cs UseEndpoints)
- When removing one of the route declarations it calls the Index method after the POST, the id parameters isn't bound and the thread culture is set wrong.

The solution for the first issue (thanks to ChatGPT) is to create one route using a regex, but nevertheless it should work when declaring it in multiple steps.
`endpoints.MapControllerRoute(
                            "My custom controller",
                            "/{lang:regex(fr|nl)}/{homeSegment:regex(maison|thuis)}/{id}",
                            new { Controller = "MyHome", Action = "Index" })
                            .ForUmbracoPage(FindContent);`

https://we.tl/t-lDH8tGvNBo
