### ISSUE TITLE
v8 - UmbracoForms - Saving data to a doc type

### ISSUE THREAD

**Issue by tyradeveloper** [umbraco/Umbraco.Forms.Issues#156]
We receive a problem when we try to save data from an umbraco form to a doc type.

The error we receive is:

`
An error occured
Multiple actions were found that match the request: 
 GetByIds on type Umbraco.Web.Editors.EntityController
 GetByIds on type Umbraco.Web.Editors.EntityController
 GetByIds on type Umbraco.Web.Editors.EntityController

Exception Details
System.InvalidOperationException: Multiple actions were found that match the request: 
 GetByIds on type Umbraco.Web.Editors.EntityController
 GetByIds on type Umbraco.Web.Editors.EntityController
 GetByIds on type Umbraco.Web.Editors.EntityController
`

Stacktrace:

`
at System.Web.Http.Controllers.ApiControllerActionSelector.ActionSelectorCacheItem.SelectAction(HttpControllerContext controllerContext)
   at System.Web.Http.Controllers.ApiControllerActionSelector.SelectAction(HttpControllerContext controllerContext)
   at Umbraco.Web.WebApi.ParameterSwapControllerActionSelector.SelectAction(HttpControllerContext controllerContext)
   at System.Web.Http.ApiController.ExecuteAsync(HttpControllerContext controllerContext, CancellationToken cancellationToken)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
`

Best regards,

**Comment by bergmania** [comment]
Hi @tyradeveloper,
I need some more information to be able to reproduce.

I gave it a try, but cannot reproduce. My setup was like this:
![image](https://user-images.githubusercontent.com/1561480/57606173-a4983d80-7568-11e9-99c8-5632fffff307.png)
![image](https://user-images.githubusercontent.com/1561480/57606201-b11c9600-7568-11e9-9c65-f1388011b77d.png)
![image](https://user-images.githubusercontent.com/1561480/57606231-c09bdf00-7568-11e9-8403-845cec4e8da2.png)
![image](https://user-images.githubusercontent.com/1561480/57606251-cb567400-7568-11e9-875c-b4d16ddbd08b.png)

**Comment by bergmania** [comment]
@tyradeveloper, This issue https://github.com/umbraco/Umbraco.Forms.Issues/issues/162 gave some more description.

It looks like you document type has an unsupported mapping.  E.g. FileUpload into MediaPicker.
How are you doc type-form entry mapping?

**Comment by ArnoldV** [comment]
Is saving to variant doctypes currently not possible by default setup?

```
"System.InvalidOperationException: Cannot save content with an empty name.
   at Umbraco.Core.Persistence.Repositories.Implement.DocumentRepository.EnsureInvariantNameExists(IContent content)
   at Umbraco.Core.Persistence.Repositories.Implement.DocumentRepository.SanitizeNames(Content content, Boolean publishing)
   at Umbraco.Core.Persistence.Repositories.Implement.DocumentRepository.PersistNewItem(IContent entity)
   at Umbraco.Core.Cache.DefaultRepositoryCachePolicy`2.Create(TEntity entity, Action`1 persistNew)
   at Umbraco.Core.Services.Implement.ContentService.Save(IContent content, Int32 userId, Boolean raiseEvents)
   at Umbraco.Forms.Core.Providers.WorkflowTypes.SaveAsUmbracoNode.Execute(Record record, RecordEventArgs e)
   at Umbraco.Forms.Core.WorkflowType.ExecuteWorkflow(Record record, RecordEventArgs e, IWorkflow workflow)
   at Umbraco.Forms.Core.Services.WorkflowService.ExecuteWorkflows(List`1 workflows, RecordEventArgs e)"
```

Might work when creating custom workflow then though?

**Comment by bergmania** [comment]
@ArnoldV 
It is not supported by default - you will need a custom workflow..
Where you define what should happen with all variants.

**Comment by ahwm** [comment]
I just ran into this. I'm not using variants or anything "fancy" just a content picker.

![image](https://user-images.githubusercontent.com/20478373/95921844-47ad4200-0d6f-11eb-8582-dd75347e0f1d.png)

I have a Prevalue Source set up like so to pull data from the node and going into the matching content picker field in the doctype above:
![image](https://user-images.githubusercontent.com/20478373/95921906-66133d80-0d6f-11eb-925f-10153ed6cf34.png)

Here is how the dropdown is set up:
![image](https://user-images.githubusercontent.com/20478373/95922054-af638d00-0d6f-11eb-8155-35908129570c.png)

And the workflow:
![image](https://user-images.githubusercontent.com/20478373/95922083-c1ddc680-0d6f-11eb-9d23-48dfacba5bce.png)

Incidentally, I'm curious how to make the Node Name more dynamic - such as using a combination of like Team and Week, for example. The documentation seems a bit lacking in this area.
