### ISSUE TITLE
Grid Control "Form" doesn't render on front-end (The partial view '/app_plugins/umbracoforms/backoffice/grideditors/formpicker.cshtml' was not found)

### ISSUE THREAD

**Issue by hfloyd** [umbraco/Umbraco.Forms.Issues#244]
If I use the "Form" grid control to insert a form on a Content node, then view the page front-end, I see an error message:

```
System.InvalidOperationException: The partial view '/app_plugins/umbracoforms/backoffice/grideditors/formpicker.cshtml' was not found or no view engine supports the searched locations. The following locations were searched:
/app_plugins/umbracoforms/backoffice/grideditors/formpicker.cshtml
   at System.Web.Mvc.HtmlHelper.FindPartialView(ViewContext viewContext, String partialViewName, ViewEngineCollection viewEngineCollection)
   at System.Web.Mvc.HtmlHelper.RenderPartialInternal(String partialViewName, ViewDataDictionary viewData, Object model, TextWriter writer, ViewEngineCollection viewEngineCollection)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
   at ASP._Page_Views_Partials_Grid_Editors_Base_cshtml.Execute() in C:\..\MyProject.Web\Views\Partials\Grid\Editors\Base.cshtml:line 20
```
If I use the "Macro" Grid control, and select the "Insert Form with Theme" macro, it renders without issue.

I don't see an entry for this "Form" Grid control in the "/config/grid.editors.config.js" file. How can I remove this as a Grid control so back-office users don't try to use it?

Umbraco v 8.2.0, Umbraco Cloud
Forms v 8.2.0

**Comment by hfloyd** [comment]
So, The rendering issue with the Form Grid Control was actually caused by Skybrud.Umbraco.GridData (the "render" attribute of the editor JSON wasn't getting interpreted properly), and was fixed there (https://github.com/skybrud/Skybrud.Umbraco.GridData/issues/29)

Incidentally, I also figured out how to remove this from the GridEditors popup - it's possible to delete the "GridEditors" section in the package.manifest in the App_Plugin, and then it won't get added to the available Grid Editors.
