### ISSUE TITLE
Redirection to page outside the umbraco doesn't work in umbraco forms

### ISSUE THREAD

**Issue by sumedhashyam** [umbraco/Umbraco.Forms.Issues#30]
Hello Guys,
I have added a workflow to Umbraco form to redirect to a page outside the Umbraco. Redirection works fine in all browser but in Firefox redirection don't work. 

My log is showing following error
2018-09-25 05:09:22,367 [P22904/D2/T27] ERROR Umbraco.Forms.Core.Providers.WorkflowTypes.PostToUrl - There was a problem sending the Record with unique id '5f1d57db-a7b4-478b-8f15-e1730fb1e308' from the Form 'News Letter English' with id '9a9f10c8-b138-41dd-941a-08cd9b418bdf' to the URL Endpoint 'https://xyz.com/client#/signup?email=' with the method 'GET'
System.Net.WebException: An exception occurred during a WebClient request. ---> System.Net.ProtocolViolationException: Cannot send a content-body with this verb-type.
at System.Net.HttpWebRequest.CheckProtocol(Boolean onRequestStream)
at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
at System.Net.HttpWebRequest.GetRequestStream()
at System.Net.WebClient.UploadBits(WebRequest request, Stream readStream, Byte[] buffer, Int32 chunkSize, Byte[] header, Byte[] footer, CompletionDelegate uploadCompletionDelegate, CompletionDelegate downloadCompletionDelegate, AsyncOperation asyncOp)
at System.Net.WebClient.UploadValues(Uri address, String method, NameValueCollection data)
--- End of inner exception stack trace ---
at System.Net.WebClient.UploadValues(Uri address, String method, NameValueCollection data)
at System.Net.WebClient.UploadValues(String address, String method, NameValueCollection data)
at Umbraco.Forms.Core.Providers.WorkflowTypes.PostToUrl.Execute(Record record, RecordEventArgs e)

### Steps to reproduce
- Add a workflow
- Select "Send form to URL" option
- Enter a URL and set Method to GET.
- Add this form to a page.
- Open page URL in firefox, try to submit and check if it's redirecting to the URL

### Specifics
- Firefox
- It's working in all other browsers

**Comment by bergmania** [comment]
Hi @sumedhashyam,

Are you able to provide a recording of what happens?

The "Send form to URL" are intented to send an async webhook to the specified url. Not redirecting the end user.

By the way, I still think that there is an issue with the "Send from to URL" when using GET, but fixing that will not end up redirecting the user in the browser.

**Comment by warrenbuckley** [comment]
The underlying error has been fixed and will do a successful GET to the URL specified and was tested with RequestBin - https://requestbin.fullcontact.com

As @bergmania mentions @sumedhashyam this feature does not do a physical redirect but sends the request of the form as a GET request in the background so another API or service could receive the data
