### ISSUE TITLE
Form submissions fail in latest version

### ISSUE THREAD

**Issue by tomvanenckevort** [umbraco/Umbraco.Forms.Issues#342]
In Forms v8.4.0 the form submissions have stopped working and it will throw an error when trying to submit a form entry.

Reproduction
------------

### Bug summary

When submitting a form the submission fails with an error that indicates that it fails to save the data into the database. It looks like it might be a mismatch between the NPoco call that Forms is making and the call that Umbraco v8 is expecting.
The same error is briefly mentioned in another issue that has been closed recently: #120

### Specifics
- Umbraco v8.5.3
- Umbraco Forms v8.4.0

### Steps to reproduce
- Create a simple form with a single textfield
- Add it to an Umbraco page (either via a macro or into a template view)
- Go to the page and fill in the form and click the submit button
- See the error appear

### Expected result
The form to be submitted and the thank you message or page to be shown.

### Actual result
The following error message is displayed:

```
System.InvalidCastException: Unable to cast object of type 'Umbraco.Core.Persistence.FaultHandling.RetryDbConnection' to type 'System.Data.SqlClient.SqlConnection'.
   at NPoco.SqlBulkCopyHelper.<>c.<.cctor>b__7_0(DbConnection dbConn)
   at NPoco.SqlBulkCopyHelper.BulkInsert[T](IDatabase db, IEnumerable`1 list, SqlBulkCopyOptions sqlBulkCopyOptions)
   at NPoco.Database.InsertBulk[T](IEnumerable`1 pocos)
   at Umbraco.Forms.Core.Data.Storage.RecordFieldStorage.InsertRecordFields(IEnumerable`1 recordFields)
   at Umbraco.Forms.Core.Data.Storage.RecordStorage.InsertRecord(Record record, Form form)
   at Umbraco.Forms.Core.Services.RecordService.StoreRecord(Record record, Form form)
   at Umbraco.Forms.Core.Services.RecordService.Approve(Record record, Form form)
   at Umbraco.Forms.Core.Services.RecordService.Submit(Record record, Form form)
   at Umbraco.Forms.Web.Controllers.UmbracoFormsController.SubmitForm(Form form, FormViewModel model, Dictionary`2 state, ControllerContext context)
   at Umbraco.Forms.Web.Controllers.UmbracoFormsController.GoForward(Form form, FormViewModel model, Dictionary`2 state)
   at Umbraco.Forms.Web.Controllers.UmbracoFormsController.HandleForm(FormViewModel model)
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c.<BeginInvokeSynchronousActionMethod>b__9_0(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_0.<InvokeActionMethodFilterAsynchronouslyRecursive>b__0()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()
```

### Workaround
I've been able to get round this bug for now by downgrading Forms back to v8.3.2.

**Comment by ronaldbarendse** [comment]
Looking at https://github.com/umbraco/Umbraco.Forms.Issues/issues/120#issuecomment-608350732, this only seems to occur on Umbraco Cloud (or any other database that uses the `RetryDbConnection`). That's probably why it wasn't discovered while testing locally and got shipped as version 8.4.0.

As Forms is shipped out of the box on Cloud, it would be very bad if this combination wasn't correctly tested at all (especially because submitting a form is the most basic test/required functionality).

**Comment by tomvanenckevort** [comment]
@ronaldbarendse I agree that it's fairly astonishing that this wasn't tested properly (it happened for me locally with a SQL Server DB), but I also find it strange that there haven't been more issue reports by other devs since Forms v8.4.0 has been out for three weeks now and has had over 1000 downloads on Nuget.

**Comment by nul800sebastiaan** [comment]
Of course we've tested this on Cloud.. just to make sure I did another test but I can't get it to fail.

![342](https://user-images.githubusercontent.com/304656/79981143-745d5c80-84a4-11ea-82bf-b289cbd8ad70.gif)

I also tried to resubmit the form a bunch of times in rapid succession.

That said, there is some database-related changes in Forms 8.4.0 so we'll have to look into that.

**Comment by tomvanenckevort** [comment]
@nul800sebastiaan Someone else on the Umbracians Slack channel mentioned it was fixed when using Umbraco v8.6.1 with Forms v8.4.0. Judging by your screenshot that Cloud test site uses v8.6.0?

So maybe it's only an issue when using Forms v8.4.0 with an Umbraco site from before v8.6.*?

**Comment by nul800sebastiaan** [comment]
Yep, just found it as well, the DB problem was fixed in Umbraco 8.6, we're using a method in Forms that doesn't work correctly in 8.5! :-(

Updating this now, should be an easy fix!

**Comment by nul800sebastiaan** [comment]
Alright, that's been updated now and a new build is available below. It would be awesome if you could give it a test run (you only need the dlls).
We're releasing 8.4.1 soon, I assume early next week. I'm sorry for the inconvenience!

[UmbracoForms.Files.8.4.1-alpha.20200422.5.zip](https://github.com/umbraco/Umbraco.Forms.Issues/files/4516268/UmbracoForms.Files.8.4.1-alpha.20200422.5.zip)

**Comment by tomvanenckevort** [comment]
@nul800sebastiaan Yes, that fix seems to work here. Thanks for getting it sorted quickly and I'll look forward to new release next week 👍

**Comment by ronaldbarendse** [comment]
Good to hear it's only a problem with Umbraco < 8.6.0 and Forms == 8.4.0. Might be worth adding to the [release notes](https://our.umbraco.com/packages/developer-tools/umbraco-forms/) though 👍

Would unchecking the `Yes, keep submitted records in a database so they can be viewed and exported later` setting of a form be a possible workaround, as that shouldn't cause any database interaction?
