### ISSUE TITLE
The SenderEmail field is allowed to be null, which can be a problem when workflows parse it

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco.Forms.Issues#344]
Resulting in the following error:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Umbraco.Forms.Data.StringHelper.ParseRecordPlaceholders(String value, IRecord record) in C:\UmbracoRepos\Forms-v7\Forms\Umbraco.Forms.Core\Data\StringHelper.cs:line 255
   at Umbraco.Forms.Data.StringHelper.ParsePlaceHolders(HttpContext context, Record record, String value) in C:\UmbracoRepos\Forms-v7\Forms\Umbraco.Forms.Core\Data\StringHelper.cs:line 322
   at Umbraco.Forms.Data.StringHelper.ParsePlaceHolders(Record record, String value) in C:\UmbracoRepos\Forms-v7\Forms\Umbraco.Forms.Core\Data\StringHelper.cs:line 311
   at Umbraco.Forms.Core.Services.WorkflowService.ExecuteWorkflows(List`1 workflows, RecordEventArgs e) in C:\UmbracoRepos\Forms-v7\Forms\Umbraco.Forms.Core\Services\WorkflowService\WorkflowService.cs:line 64
   at Umbraco.Forms.Core.Services.WorkflowService.ExecuteWorkflows(Record record, Form form, FormState state, Boolean editMode) in C:\UmbracoRepos\Forms-v7\Forms\Umbraco.Forms.Core\Services\WorkflowService\WorkflowService.cs:line 34
   at Umbraco.Forms.Web.Services.RecordService.Submit(Record record, Form form)
   at Umbraco.Forms.Web.Controllers.UmbracoFormsController.SubmitForm(Form form, FormViewModel model, Dictionary`2 state, ControllerContext context)
   at Umbraco.Forms.Web.Controllers.UmbracoFormsController.GoForward(Form form, FormViewModel model, Dictionary`2 state)
   at Umbraco.Forms.Web.Controllers.UmbracoFormsController.HandleForm(FormViewModel model, Boolean captchaIsValid)
   at lambda_method(Closure , ControllerBase , Object[] )
```

It's possible that other workflows also accept `null` settings so we'll check for that.

For example, from the email xlst workflow:

> Enter the sender email (if blank it will use the settings from /config/umbracosettings.config)

![image](https://user-images.githubusercontent.com/304656/80578406-b177a080-8a08-11ea-932a-d31142debc76.png)

**Comment by nul800sebastiaan** [comment]
Note: the workaround for now is: fill in the `Sender Email` field. 🙂
