### ISSUE TITLE
Insert Test Form into Rich Text Editor

### ISSUE THREAD

**Issue by Kinaetron** [umbraco/Umbraco.Forms.Issues#354]
I've installed UmbracoForms 7.4.1 from Nuget on Umbraco version 7.12.1. On trying to insert the test form into a content page via the RTE, Umbraco threw out an error message and stacktrace which you can see below. I noticed that when I went onto the Forms section of backoffice I saw that backoffice thinks Umbraco Forms 7.0.3 i installed.

which looks like a mismatch on the version I installed via Nuget

```
Error executing child request for handler 'System.Web.Mvc.HttpHandlerUtil+ServerExecuteHttpHandlerAsyncWrapper'

Stacktrace

at System.Web.HttpServerUtility.ExecuteInternal(IHttpHandler handler, TextWriter writer, Boolean preserveForm, Boolean setPreviousPage, VirtualPath path, VirtualPath filePath, String physPath, Exception error, String queryStringOverride)

   at System.Web.HttpServerUtility.Execute(IHttpHandler handler, TextWriter writer, Boolean preserveForm, Boolean setPreviousPage)

   at System.Web.HttpServerUtility.Execute(IHttpHandler handler, TextWriter writer, Boolean preserveForm)

   at System.Web.Mvc.Html.ChildActionExtensions.ActionHelper(HtmlHelper htmlHelper, String actionName, String controllerName, RouteValueDictionary routeValues, TextWriter textWriter)

   at System.Web.Mvc.Html.ChildActionExtensions.RenderAction(HtmlHelper htmlHelper, String actionName, String controllerName, Object routeValues)

   at ASP._Page_Views_MacroPartials_InsertUmbracoFormWithTheme_cshtml.Execute() in C:\Work\...\Views\MacroPartials\InsertUmbracoFormWithTheme.cshtml:line 48

   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()

   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()

   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)

   at Umbraco.Core.Profiling.ProfilingView.Render(ViewContext viewContext, TextWriter writer)

   at Umbraco.Web.Mvc.ControllerExtensions.RenderViewResultAsString(ControllerBase controller, ViewResultBase viewResult)

   at Umbraco.Web.Macros.PartialViewMacroEngine.Execute(MacroModel macro, IPublishedContent content)

   at umbraco.macro.LoadPartialViewMacro(MacroModel macro)

   at umbraco.macro.renderMacro(Hashtable pageElements, Int32 pageId)

   at Umbraco.Web.UmbracoComponentRenderer.RenderMacro(macro m, IDictionary`2 parameters, page umbracoPage)

   at Umbraco.Web.Editors.MacroController.GetMacroResultAsHtml(String macroAlias, Int32 pageId, IDictionary`2 macroParams)

   at lambda_method(Closure , Object , Object[] )

   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.<GetExecutor>b__3(Object instance, Object[] methodParameters)

   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()

Inner Exception
System.Web.HttpCompileException: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\cee63a63\317dd5fe\App_Web_render.cshtml.e38f7875.phrmr5hi.0.cs(50): error CS0246: The type or namespace name 'WebViewPage<>' could not be found (are you missing a using directive or an assembly reference?)

at System.Web.Compilation.AssemblyBuilder.Compile()

   at System.Web.Compilation.BuildProvidersCompiler.PerformBuild()

   at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath)

   at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)

   at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)

   at System.Web.Compilation.BuildManager.GetVirtualPathObjectFactory(VirtualPath virtualPath, HttpContext context, Boolean allowCrossApp, Boolean throwIfNotFound)

   at System.Web.Compilation.BuildManager.GetCompiledType(VirtualPath virtualPath)

   at System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer)

   at Umbraco.Core.Profiling.ProfilingView.Render(ViewContext viewContext, TextWriter writer)

   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)

   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)

   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)

   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)

   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)

   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)

   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)

   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_1.<BeginInvokeAction>b__5(IAsyncResult asyncResult)

   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)

   at System.Web.Mvc.Controller.<>c.<BeginExecuteCore>b__152_1(IAsyncResult asyncResult, ExecuteCoreState innerState)

   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)

   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)

   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)

   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)

   at System.Web.Mvc.MvcHandler.<>c.<BeginProcessRequest>b__20_1(IAsyncResult asyncResult, ProcessRequestState innerState)

   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)

   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)

   at System.Web.Mvc.HttpHandlerUtil.ServerExecuteHttpHandlerWrapper.<>c__DisplayClass5_0.<Wrap>b__0()

   at System.Web.Mvc.HttpHandlerUtil.ServerExecuteHttpHandlerWrapper.Wrap[TResult](Func`1 func)

   at System.Web.HttpServerUtility.ExecuteInternal(IHttpHandler handler, TextWriter writer, Boolean preserveForm, Boolean setPreviousPage, VirtualPath path, VirtualPath filePath, String physPath, Exception error, String queryStringOverride)
```

---
_This item has been added to our backlog [AB#6942](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/6942)_

**Comment by nul800sebastiaan** [comment]
I'm not sure what to tell you.. if the backoffice tells you Forms 7.0.3 installed then it's very likely that Forms 7.0.3 is installed.

Make sure to verify that you have the correct version installed, a way to do that is to download `UmbracoForms.Files.7.4.1.zip` from https://our.umbraco.com/packages/developer-tools/umbraco-forms/ and compare that the files from that zip file match the files in your site.

**Comment by Kinaetron** [comment]
Honestly I would be a tad worried that your Nuget Package is installing the wrong version of Umbraco Forms
![Nuget Package](https://user-images.githubusercontent.com/9024673/81703751-e9e59880-9464-11ea-80d0-36ce676598fb.PNG)

**Comment by nul800sebastiaan** [comment]
@Kinaetron 7.4.1 is the correct version for Umbraco 7, so that's expected behavior! Unless it installed Forms v8 for you?

**Comment by Kinaetron** [comment]
When I looked into Umbraco Forms on the back office it said 7.0.3 of Umbraco Forms was installed. I then went back and directly installed Umbraco Forms 7.4.1 which showed shows the correct version of Umbraco Forms, but didn't fix my issue I talked about in this ticket

**Comment by nul800sebastiaan** [comment]
I don't know how you ended up with 7.0.3, not sure how that would happen.

I get the following result when inserting a Form with Forms 7.4.1 into an Umbraco 7.12.1 site, so I have to suspect something is going wrong in your specific site implementation:

![Forms354](https://user-images.githubusercontent.com/304656/81784742-9a06e000-94fd-11ea-9a11-1e553369bf28.gif)

I also tried the same thing with Forms version 7.0.3 on this 7.12.1 site and it gives me the same result, so that was my mistake assuming that it was due to a Forms version problem.

If you have any other steps to reproduce this then that would be great, we just don't have enough information now to look further into it.

**Comment by Kinaetron** [comment]
@nul800sebastiaan I added the frontend scripts to the master template and then tried to add the default test form that comes with Umbraco Forms. 

Is there any other steps I need to follow in order to be able to add forms via the RTE ?

**Comment by nul800sebastiaan** [comment]
Yeah, that's all I did as well, I have no idea what's going on.. what does your form definition look like, can you post it? `\App_Data\UmbracoForms\Data\forms\*.json`

**Comment by Kinaetron** [comment]
@nul800sebastiaan Sorry about the slow reply I got pulled onto another project. here is the json file you asked for.

```
{
  "name": "Contact Us",
  "created": "2020-05-11T15:55:59.6228778+01:00",
  "pages": [
    {
      "fieldSets": [
        {
          "caption": "Personal",
          "sortOrder": 0,
          "id": "44e26e06-d832-4b8b-8123-20ed277cc392",
          "page": "00000000-0000-0000-0000-000000000000",
          "containers": [
            {
              "caption": null,
              "width": 12,
              "fields": [
                {
                  "caption": "Name",
                  "tooltip": "Full Name",
                  "placeholder": null,
                  "cssClass": null,
                  "alias": "name",
                  "id": "7eaf3f46-769c-4ffa-eef8-785718784da8",
                  "fieldTypeId": "3f92e01b-29e2-4a30-bf33-9df5580ed52c",
                  "prevalueSourceId": "00000000-0000-0000-0000-000000000000",
                  "dataSourceFieldKey": null,
                  "containsSensitiveData": false,
                  "mandatory": true,
                  "regex": null,
                  "requiredErrorMessage": "Please enter a name",
                  "invalidErrorMessage": null,
                  "condition": {
                    "id": "00000000-0000-0000-0000-000000000000",
                    "enabled": false,
                    "actionType": "Show",
                    "logicType": "All",
                    "rules": []
                  },
                  "settings": {
                    "Placeholder": "name"
                  },
                  "preValues": []
                },
                {
                  "caption": "Email",
                  "tooltip": null,
                  "placeholder": null,
                  "cssClass": null,
                  "alias": "email",
                  "id": "68ad02fe-eb3b-425b-e703-e800e51b3d80",
                  "fieldTypeId": "3f92e01b-29e2-4a30-bf33-9df5580ed52c",
                  "prevalueSourceId": "00000000-0000-0000-0000-000000000000",
                  "dataSourceFieldKey": null,
                  "containsSensitiveData": false,
                  "mandatory": true,
                  "regex": "[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+.[a-zA-Z0-9-.]+",
                  "requiredErrorMessage": "Please enter your email",
                  "invalidErrorMessage": null,
                  "condition": {
                    "id": "00000000-0000-0000-0000-000000000000",
                    "enabled": false,
                    "actionType": "Show",
                    "logicType": "All",
                    "rules": []
                  },
                  "settings": {
                    "Placeholder": "your@email.com"
                  },
                  "preValues": []
                },
                {
                  "caption": "What is your favourite colour",
                  "tooltip": null,
                  "placeholder": null,
                  "cssClass": null,
                  "alias": "whatIsYourFavouriteColour",
                  "id": "1a4fe67b-4613-4bbf-ea40-65e0c5727df5",
                  "fieldTypeId": "fab43f20-a6bf-11de-a28f-9b5755d89593",
                  "prevalueSourceId": "00000000-0000-0000-0000-000000000000",
                  "dataSourceFieldKey": null,
                  "containsSensitiveData": false,
                  "mandatory": false,
                  "regex": null,
                  "requiredErrorMessage": null,
                  "invalidErrorMessage": null,
                  "condition": {
                    "id": "00000000-0000-0000-0000-000000000000",
                    "enabled": false,
                    "actionType": "Show",
                    "logicType": "All",
                    "rules": []
                  },
                  "settings": {},
                  "preValues": [
                    "Red",
                    "Blue",
                    "Green"
                  ]
                }
              ]
            }
          ],
          "condition": null
        },
        {
          "caption": "Family",
          "sortOrder": 0,
          "id": "af96f591-6185-458e-98e1-717e084e12d6",
          "page": "00000000-0000-0000-0000-000000000000",
          "containers": [
            {
              "caption": "",
              "width": 12,
              "fields": [
                {
                  "caption": "Do you have siblings",
                  "tooltip": null,
                  "placeholder": null,
                  "cssClass": null,
                  "alias": "doYouHaveSiblings",
                  "id": "6852ca70-0fc4-4393-e439-dbb9751f72e9",
                  "fieldTypeId": "d5c0c390-ae9a-11de-a69e-666455d89593",
                  "prevalueSourceId": "00000000-0000-0000-0000-000000000000",
                  "dataSourceFieldKey": null,
                  "containsSensitiveData": false,
                  "mandatory": false,
                  "regex": null,
                  "requiredErrorMessage": null,
                  "invalidErrorMessage": null,
                  "condition": {
                    "id": "00000000-0000-0000-0000-000000000000",
                    "enabled": false,
                    "actionType": "Show",
                    "logicType": "All",
                    "rules": []
                  },
                  "settings": {},
                  "preValues": []
                }
              ]
            }
          ],
          "condition": null
        }
      ],
      "caption": "Page 1",
      "sortOrder": 0,
      "id": "00000000-0000-0000-0000-000000000000",
      "form": "00000000-0000-0000-0000-000000000000"
    },
    {
      "fieldSets": [
        {
          "caption": "",
          "sortOrder": 0,
          "id": "aad1a0c1-785f-4028-c412-541cfa6f1a8d",
          "page": "00000000-0000-0000-0000-000000000000",
          "containers": [
            {
              "caption": "",
              "width": 12,
              "fields": [
                {
                  "caption": "Tell us about yourself",
                  "tooltip": null,
                  "placeholder": null,
                  "cssClass": null,
                  "alias": "tellUsAboutYourself",
                  "id": "017cdf52-9250-4639-e582-656ab3b9164a",
                  "fieldTypeId": "023f09ac-1445-4bcb-b8fa-ab49f33bd046",
                  "prevalueSourceId": "00000000-0000-0000-0000-000000000000",
                  "dataSourceFieldKey": null,
                  "containsSensitiveData": false,
                  "mandatory": false,
                  "regex": null,
                  "requiredErrorMessage": null,
                  "invalidErrorMessage": null,
                  "condition": {
                    "id": "00000000-0000-0000-0000-000000000000",
                    "enabled": false,
                    "actionType": "Show",
                    "logicType": "All",
                    "rules": []
                  },
                  "settings": {},
                  "preValues": []
                }
              ]
            }
          ],
          "condition": null
        }
      ],
      "caption": "Page 2",
      "sortOrder": 0,
      "id": "00000000-0000-0000-0000-000000000000",
      "form": "00000000-0000-0000-0000-000000000000"
    }
  ],
  "id": "ec36c5ad-1511-48b4-ad35-dec120658832",
  "fieldIndicationType": "MarkMandatoryFields",
  "indicator": "*",
  "showValidationSummary": false,
  "hideFieldValidation": false,
  "requiredErrorMessage": "Please provide a value for {0}",
  "invalidErrorMessage": "Please provide a valid value for {0}",
  "messageOnSubmit": "Thank you",
  "goToPageOnSubmit": 0,
  "xPathOnSubmit": null,
  "manualApproval": false,
  "storeRecordsLocally": true,
  "cssClass": null,
  "disableDefaultStylesheet": false,
  "useClientDependency": false,
  "workflows": [
    "dc89832f-02e6-43c0-93dd-d52f853c1757"
  ],
  "datasource": null,
  "submitLabel": "Submit",
  "nextLabel": "Next",
  "prevLabel": "Previous"
}
```

**Comment by nul800sebastiaan** [comment]
Thanks again @Kinaetron. I am afraid that this one works for me just fine, I'm not sure what is going on. 

![354](https://user-images.githubusercontent.com/304656/83000721-0a882380-a00b-11ea-8d37-3d61acb1eb6b.gif)

The only thing I can suggest for now is to disable rendering the macro in the rich text editor as that's where the error seems to be coming  from:

![image](https://user-images.githubusercontent.com/304656/83000932-51761900-a00b-11ea-9f26-fadeb4947719.png)

**Comment by nul800sebastiaan** [comment]
Aha! I must apologize @Kinaetron for the confusion here, all this time I was testing on version 8.5.5 not on 8.6.1. 🤦‍♂️

I think I have found the issue which was introduced in 8.6.0 with this line of code: https://github.com/umbraco/Umbraco-CMS/pull/6627/

Previously, we would use the preview of the page to fetch the macro rendering, but now that is not longer the case, we just try to get the content item directly, but it doesn't exist so we can't. 

We'll investigate! Apologies for the confusion!

**Comment by thomasandresen** [comment]
The issue has been fixed and will be included in release 8.7

**Comment by Kinaetron** [comment]
@nul800sebastiaan So in order to try and sort out some of our problems Umbraco my team decided to update to umbraco 7.15.5. I was hoping that this would help solve our issue with Umbraco Forms, but unfortunately this isn't the case.

**Comment by nul800sebastiaan** [comment]
Hmm, it looks like I got a bit confused here between v8 and v7 of Umbraco! You inadvertently discovered a bug in Umbraco 8 though 🙈 

I am not sure what to tell you about your Umbraco v7/Forms v7 issue then, sorry that I missed that important detail. Does disabling rendering the macro in the RTE help for you though?
The same bug that was in v8 is not present in v7 of Umbraco so that's not the problem. 

As I [showed in a previous comment](https://github.com/umbraco/Umbraco.Forms.Issues/issues/354#issuecomment-634535381) I have you form working just fine. I'm afraid there's something "wrong" in your particular setup but I wouldn't know where to start on that one ☹

**Comment by Kinaetron** [comment]
@nul800sebastiaan disabling rendering didn't really help as while the error did disappear in the backoffice, the element still didn't show up in page I expected it to. Is there a way of escalating this further as I can't find anything on our side that would break this and we really do need this form working on our site

**Comment by nul800sebastiaan** [comment]
> the element still didn't show up in page I expected it to.

It didn't show up at all? Or do you have an error there as well. 

Unfortunately I can't troubleshoot this here, I would recommend you contact Forms support and point them to this issue. I believe the only way to dig in deeper from now on is if they could get a copy of your site + database, so that support can start debugging the problem.

You can head on over to the support area and log in with the account that purchased Forms: https://shop.umbraco.com/profile/options/get-help-and-support/

**Comment by Kinaetron** [comment]
Thanks I'II do as you suggested
