### ISSUE TITLE
formService.Get(id) Sql Error

### ISSUE THREAD

**Issue by filefontaine** [umbraco/Umbraco.Forms.Issues#411]
If the option **StoreUmbracoFormsInDb** is set to false, the formService.Get(id) as a Sql Error.

```
System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'UFForms'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 208
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass30_0.<ExecuteDbDataReader>b__0() in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 204
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass33_0`1.<Execute>b__0() in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 222
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryPolicy.cs:line 172
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 219
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 204
   at System.Data.Common.DbCommand.ExecuteReader()
   at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)
   at NPoco.Database.ExecuteDataReader(DbCommand cmd)
   at NPoco.Database.<QueryImp>d__164`1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at NPoco.Database.FirstOrDefault[T](Sql sql)
   at Umbraco.Forms.Core.Persistence.Repositories.Implement.FormRepository.PerformGet(Guid id)
   at Umbraco.Core.Cache.NoCacheRepositoryCachePolicy`2.Get(TId id, Func`2 performGet, Func`2 performGetAll) in D:\a\1\s\src\Umbraco.Core\Cache\NoCacheRepositoryCachePolicy.cs:line 17
ClientConnectionId:XXX
Error Number:208,State:1,Class:16
```

For get the form we need to do :
 formStorage.GetForm(GUID)

But is set as Obselete.

Have you another solution or the best is to set up **StoreUmbracoFormsInDb** as True

---
_This item has been added to our backlog [AB#8726](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8726)_

**Comment by nul800sebastiaan** [comment]
I am not sure why the GUID version would be obsolete, that's definitely the one we should prefer! I'll have to have a look, please keep using `formStorage.GetForm(GUID)`.

**Comment by nul800sebastiaan** [comment]
Alright I had a look, `formService.Get(id)` goes straight to the database, it looks like we don't check if `StoreUmbracoFormsInDb` is true or false, we'll have to fix that up.

**Comment by nul800sebastiaan** [comment]
For now, using `formStorage.GetForm(GUID)` is recommended for you.

**Comment by OnlinePseudonym** [comment]
@nul800sebastiaan I'm still getting that error when using formService.GetForm(GUID) in 8.5.3. I had to downgrade to 8.4.2

**Comment by filefontaine** [comment]
Hello @OnlinePseudonym ,

If you haven't set the parameter **StoreUmbracoFormsInDb** as True in UmbracoFroms.config you need to use `formStorage.GetForm(GUID);` not the `formService.GetForm(GUID)` the class for the `formStorage` is `IFormStorage`.

You can get it with : 
```
using Umbraco.Forms.Core.Data.Storage;
var formStorage = Current.Factory.GetInstance<IFormStorage>();
```

**Comment by filefontaine** [comment]
@nul800sebastiaan Thanks for all, i will do that.

**Comment by OnlinePseudonym** [comment]
@filefontaine ahhh! Thanks, my brain just glossed over the class name difference! I even had to read over your comment twice to see it.

**Comment by afinn-tech** [comment]
Is this still an issue in 8.5.5 , 
System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'UFForms'.
i keep getting this error , on rebuild of the Forms index 
Index populating failed for populator "Umbraco.Forms.Core.Data.RecordIndex.FormsIndexPopulator"
?

**Comment by nul800sebastiaan** [comment]
For now you can ignore it, it's not harmful.

**Comment by warrenbuckley** [comment]
This will be due in the next version of Forms

**Comment by NicolaSA** [comment]
Hi Folks, 

Do you have advice please.

Since 27th Nov: We've gone from UmbracoForms version="8.5.5" to version="8.6.0" and this error still crops up in our log files. 
When it exceptions, it takes out the entire website front end + back office /umbraco/.

A site restart resurrects site.

1. We have key="StoreUmbracoFormsInDb" value="False". 
As it stands, I believe Umbraco articles suggest that changing this to True may be detrimental to forms health / performance, is there any clarity on this please? 

2. Oddly enough this error only appears on one of our v8 clients.:
Both of these client's sites started as blank v8 new installs, they're now both on Umbraco 8.9.1:
Client 1: Cloud: Started as Umbraco  8.2.0 (15th Oct 2019)
Client 2: Azure: Started as Umbraco  8.6.6 (Apr 2020)

Client 1, on Umbraco cloud, does not get the Exception at all:
System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'UFForms'.

Client 2: Azure client DOES get the Exception:
System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'UFForms'.
@nul800sebastiaan mentions it is not harmful.

2.2 This is either not accurate or the 2nd accompanying Exception which follows our Invalid object name 'UFForms' in the logs is the culprit?

I've included both the exceptions incase they help, they're appear almost the same except the 2nd exception with the same datetime stamp is longer.

We'll dig further on our side to see what makes our cloud client different from the azure-non cloud client but the code bases are very very similar to one another.

3. @warrenbuckley. Thanks for 5 days ago advisory of "this will be due in next version of forms with tag release/8.5.6".
Given that we're on Umbraco forms 8.6.0, would this indicate another patch relook at this is possibly required.

Thanks a mill everyone for a very useful thread.
Any help / input on ?'s in my post for  #1, #2.2 and #3 would be super appreicated.
We're under pressure from both the external client and internal managers to report back on this.

Standing by,
Nix

+++
1st:
Exception ("0ddf242f").
+++
System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'UFForms'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 208
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass30_0.<ExecuteDbDataReader>b__0() in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 204
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass33_0`1.<Execute>b__0() in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 222
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryPolicy.cs:line 172
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 219
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 204
   at System.Data.Common.DbCommand.ExecuteReader()
   at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)
   at NPoco.Database.ExecuteDataReader(DbCommand cmd)
ClientConnectionId:bedaae85-553f-46fd-9f14-5feba759c5b7
Error Number:208,State:1,Class:16
ClientConnectionId before routing:7c833256-4abb-4406-be28-d001e72e06ea
Routing Destination:f9eb1e26d477.tr2338.westeurope1-a.worker.database.windows.net,11056

+++
2nd:
Index populating failed for populator "Umbraco.Forms.Core.Data.RecordIndex.FormsIndexPopulator"
+++
System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'UFForms'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 208
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass30_0.<ExecuteDbDataReader>b__0() in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 204
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass33_0`1.<Execute>b__0() in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 222
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryPolicy.cs:line 172
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 219
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 204
   at System.Data.Common.DbCommand.ExecuteReader()
   at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)
   at NPoco.Database.ExecuteDataReader(DbCommand cmd)
ClientConnectionId:bedaae85-553f-46fd-9f14-5feba759c5b7
Error Number:208,State:1,Class:16
ClientConnectionId before routing:7c833256-4abb-4406-be28-d001e72e06ea
Routing Destination:f9eb1e26d477.tr2338.westeurope1-a.worker.database.windows.net,11056

**Comment by ccampbell-nra** [comment]
I know this issue is marked "closed" but I'm building an Umbraco CMS 8.14.0 site with UForms 8.7.4 and I'm still seeing the issue. The config key "StoreUmbracoFormsInDb" is marked "False". I have a workflow helper class where I'm being directed to use:

`Form form = _formService.Get(record.Form);`

But that's throwing a SqlException.

**Comment by AndyButland** [comment]
You need to be using `IFormStorage` when working with forms stored on disk.  `IFormService` is a newer service that expects the forms in the database.  `IFormStorage` is marked as obsolete - it's been removed in V9 - but it'll be available for any subsequent releases of Umbraco Forms V8.

**Comment by MalikFarhanManzoor** [comment]
@Umbraco.RenderMacro("renderUmbracoForm". i am using RenderMarco still i am getting this error
