### ISSUE TITLE
Couldn't get the Forms version number from the version marker file, using reflection instead 

### ISSUE THREAD

**Issue by mcl-sz** [umbraco/Umbraco.Forms.Issues#448]
When a uploadfield is added to a form, the following error occures:

2020-11-11 14:32:39.463 +01:00 [Error] Couldn't get the Forms version number from the version marker file, using reflection instead
System.IO.FileNotFoundException: Could not find file 'xxxxxxx\App_plugins\umbracoForms\version'.
File name: 'xxxxxxxx\App_plugins\umbracoForms\version'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at Umbraco.Forms.Core.Configuration.GetVersion()
2020-11-11 14:32:39.635 +01:00 [Error] 'RazorViewFilePath' setting has not been set'
Parameter name: RazorViewFilePath
System.ArgumentNullException: 'RazorViewFilePath' setting has not been set'
Parameter name: RazorViewFilePath

Reproduction
------------

Add an file/upload field to a form and fill in the form. Check the logs for this error.

**Comment by nul800sebastiaan** [comment]
@mcl-sz I'm suspecting a permissions problem on the file `~/App_plugins\umbracoForms\version` - Forms tries to read it, if it doesn't exist it tries to write it. This error shows it either doesn't exist or the app pool is not allowed to read it.

This looks like an older version though, in the latest version 8.5.5 I don't have this version marker file any more, it's not needed. 

I'll close this an encourage you to do an upgrade to 8.5.5. Sticking with the current version is also fine if it works well for you, this error message doesn't affect anything really.

**Comment by PerplexDaniel** [comment]
> This looks like an older version though, in the latest version 8.5.5 I don't have this version marker file any more, it's not needed.

Actually we still see this error occur in a site running UmbracForms 8.11.0, and a quick peek in the source of UmbracoForms.Core.dll reveals the code is still checking this marker file (in `Umbraco.Forms.Core.Configuration`) but this marker file is not distributed in the NuGet package as far as we can tell (or generated on build or so).

The fallback to obtain the version from the DLL (underlined in green) seems like the way to go anyway, probably make that the only way of obtaining the version and remove all the marker file logic. In Umbraco.Forms v9 it's in `Umbraco.Forms.Core.Services.Version.VersionService`.

![image](https://user-images.githubusercontent.com/24297947/164226827-0e47e946-65aa-47b6-8873-2e60c98c912c.png)

**Comment by AndyButland** [comment]
I suspect this file was added in the past as a "cache" to avoid using reflection each time there's a need to get the product version number, so we should probably retain it.  But we can still improve things here.  For the next release (8.13/9.5) there will be an exists check before trying to read the file (so the exception will only be thrown when something exceptional has happened, and not when the file doesn't exist).
