### ISSUE TITLE
Issue after upgrading to Forms 7.4.1

### ISSUE THREAD

**Issue by teeto** [umbraco/Umbraco.Forms.Issues#453]
After upgrading from UF 7.1.3 to 7.4.1 we are having these two issues:

1) getting this error:
System.NullReferenceException on Umbraco.Forms.Data.StringHelper.ParseRecordPlaceholders(String value, IRecord record)
after sending a form with workflows attached.

2) Also on the backoffice we cant see the labels of the form and neither the placeholders 

Reproduction
------------
Update using UmbracoForms.Files.7.4.1.zip and copying all the contents but merging UmbracoForms.config
Following the steps here: https://our.umbraco.com/Documentation/Add-ons/UmbracoForms/Installation/ManualUpgrade-v7

Issue 1:
After doing this and testing a form i get this error:
System.NullReferenceException on Umbraco.Forms.Data.StringHelper.ParseRecordPlaceholders(String value, IRecord record)
after sending a form with workflows attached.

The form has some workflows, some of these are custom. If i deactivate all workflows it works without errors.
I have tried deleting the workflows and creating them again and now it works.
It is as after upgrading i should resave the workflows to clear some kind of cache?
This is a problem because we have lots of forms with workflows created and deleting all the workflows and creating them again would be a very hard job.

Issue 2:
After solving this, i enter the backoffice and i cant see any label or place holder.
I do a refresh page and sometimes they load and sometimes not. I have tried clearing the browser cache but it doesnt fix the issue.
Inspecting the label i can see this html:

`<input type="text" class="umb-locked-field__input ng-pristine ng-valid ng-valid-required" name="lockedField" ng-model="ngModel" ng-disabled="locked" ng-class="{'-unlocked': !locked}" placeholder="Alias..." val-regex="^[a-zA-Z]\w.*$" umb-auto-resize="" required="" val-server-field="field_nombre" title="nombre" focus-when="false" umb-select-when="false" on-blur="lock()" disabled="disabled" style="width: 2px;">`

Note the width: 2px, if i change it on the inspector to 40px it shows, so it seems they are hidden on the angular css.

I have tried to upgrade back to 7.1.3 and after clearing the browser cache all the labels show again.
Then i have tried to upgrade to 7.3.1 and the backoffice issue 2 it happening too.

I have tried using other browser like Firefox and the issue still occurs, have tried on chrome using private browsing and still happening.

**Comment by nul800sebastiaan** [comment]
Thanks for the report @teeto.  I'm not sure what the problem is but we've had some problems with missing null checks in the v8 branch as well, so I assume they're related. Do you have a log to look at please? I need to see what the error's call stack is so we can pinpoint the missing null check.

**Comment by teeto** [comment]
Hi @nul800sebastiaan 
I forgot to point i am using v7.15.4 and i just updated to v7.15.6 (current last v7 version) and the problem continues.
On the console inspector i dont see any js errors, what log are you referring, the umbraco log?
I attach a screen capture of the issue. If i click on reorder, then i can see the labels.
![nolabels](https://user-images.githubusercontent.com/1017314/99779446-5c6eb980-2b15-11eb-9fb6-59588257e9d8.jpg)
![after-reorder](https://user-images.githubusercontent.com/1017314/99779471-61336d80-2b15-11eb-8b0d-9adcdfd93c4d.jpg)

**Comment by teeto** [comment]
This is the error logged on the issue 1, when sending a form with workflows after updating.
The error went away when deleting and creating again the workflows:

`2020-11-17 00:52:15,585 [P6568/D19/T115] ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Umbraco.Forms.Data.StringHelper.ParseRecordPlaceholders(String value, IRecord record)
   at Umbraco.Forms.Data.StringHelper.ParsePlaceHolders(HttpContext context, Record record, String value)
   at Umbraco.Forms.Core.Services.WorkflowService.ExecuteWorkflows(List`1 workflows, RecordEventArgs e)
   at Umbraco.Forms.Core.Services.WorkflowService.ExecuteWorkflows(Record record, Form form, FormState state, Boolean editMode)
   at Umbraco.Forms.Web.Services.RecordService.Submit(Record record, Form form)
   at Umbraco.Forms.Web.Controllers.UmbracoFormsController.SubmitForm(Form form, FormViewModel model, Dictionary`2 state, ControllerContext context)
   at Umbraco.Forms.Web.Controllers.UmbracoFormsController.GoForward(Form form, FormViewModel model, Dictionary`2 state)
   at Umbraco.Forms.Web.Controllers.UmbracoFormsController.HandleForm(FormViewModel model, Boolean captchaIsValid)
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c.<BeginInvokeSynchronousActionMethod>b__9_0(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_0.<InvokeActionMethodFilterAsynchronouslyRecursive>b__0()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_6.<BeginInvokeAction>b__4()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_1.<BeginInvokeAction>b__1(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<>c.<BeginExecuteCore>b__152_1(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<>c.<BeginProcessRequest>b__20_1(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)`

**Comment by nul800sebastiaan** [comment]
Thanks @teeto that helps. I can confirm this is a bug and it was previously reported in https://github.com/umbraco/Umbraco.Forms.Issues/issues/417 and it was also a problem for v7.

I've made a nightly build of the upcoming 7.4.2 version for you with this bug fixed so you can at least move on for now: 

[UmbracoForms.Files.7.4.2-alpha-20201120-001.zip](https://github.com/umbraco/Umbraco.Forms.Issues/files/5572433/UmbracoForms.Files.7.4.2-alpha-20201120-001.zip)

I unfortunately have no expected release date of 7.4.2 yet.

**Comment by teeto** [comment]
Thanks @nul800sebastiaan  i have applied your nightly build, and i cant confirm the problem with the workflows is solved because now we cant reproduce the error, as we created again the workflows.

But the issue 2 with the labels disappeared of the forms continues....

**Comment by nul800sebastiaan** [comment]
@teeto Okay, I didn't read your issue very well, make sure to always create separate issues for things that don't seem related. I only responded to the error you posted and didn't really read much further as I assumed the rest of the report would be about that error too. 

Unfortunately I can't reproduce the problem with the labels: 

![image](https://user-images.githubusercontent.com/304656/99785644-b5dae680-2b1d-11eb-83a5-a7c1224ed221.png)

Make sure to verify that you have updated ALL of the files in the App_Plugins folder from the zip file above except for UmbracoForms.config.
I would suspect a browser caching problem, make sure to update the version in ClientDependency.config (just make it 1 higher or lower) and if that doesn't work do a hard refresh in your browser.

**Comment by teeto** [comment]
Sorry as it was related to updating to 7.4.1 i wrote them on one post.
I thought too it was a problem with cache, so i tried (and now again with the alpha) this:

- Stop IIS
- Clear cache
- Delete UmbracoForms App_Plugins folder
- Copy the new one from the alpha release.
- Copy the old UmbracoForms config file with the new version
- Increase ClientDependency.config
- Delete chrome cache temporary files
- Start IIS
- Visit forms section

But after all this the problem continues... on the chrome console does not show any js error.
I dont know what more to do...

May be this part i wrote is a clue for you, inspecting a hidden label on chrome i can see this html:

<input type="text" class="umb-locked-field__input ng-pristine ng-valid ng-valid-required" name="lockedField" ng-model="ngModel" ng-disabled="locked" ng-class="{'-unlocked': !locked}" placeholder="Alias..." val-regex="^[a-zA-Z]\w.*$" umb-auto-resize="" required="" val-server-field="field_nombre" title="nombre" focus-when="false" umb-select-when="false" on-blur="lock()" disabled="disabled" style="width: 2px;">

Note the width: 2px, if i change it on the inspector to 40px it shows, so it seems they are hidden on the angular css.
And also if i click on reorder and click again to finish reordering it shows the labels, but not the aliases or placeholders.
Also when creating a form i cant see the labels i create, but then save the form and when enter again to edit the labels disappear (see my screenshots above).

**Comment by nul800sebastiaan** [comment]
I'm afraid that doesn't ring a bell.. 😞 

I can't reproduce it on a clean Umbraco 7.15.4 / Forms 7.4.1 install so I must assume that something in your install is causing those labels to be hidden or get a too small width. In my install they get set to `width: 33px;`.

**Comment by teeto** [comment]
Hi @nul800sebastiaan , i have made a test.
A fresh umbraco installation (v7.15.6), installed Forms 7.4.1 and create a form. It looks good, labels showing.
Then i have changed connection string to the other project database (the one with the labels problem) and copy App_Plugins/UmbracoForms/Data folder and App_Data/UmbracoForms folder.
I edit the forms and no labels showing again. So my question is, may it be a database issue? maybe the update has to make something to the database that it is not done properly?
Or may it be something with the umbraco forms data on the app_plugins folder or app_data?
I dont fully understand where the forms are stored, on disk and database? if  i only change connection string the forms dont load, i have to copy the other folders...

**Comment by teeto** [comment]
@nul800sebastiaan i dont know what more can i try, any ideas?

**Comment by teeto** [comment]
I have created it as a separate issue here:
https://github.com/umbraco/Umbraco.Forms.Issues/issues/460
