### ISSUE TITLE
Urgent: The incoming request has too many parameters. The server supports a maximum of 2100 parameters. This while rebuilding the UmbracoFormsRecordsIndex

### ISSUE THREAD

**Issue by mcl-sz** [umbraco/Umbraco.Forms.Issues#470]
Because of the following error we've updated our Forms 8.4.1 to Forms 8.6.0 but the error still occures when rebuilding UmbracoFormsRecordsIndex :

**The incoming request has too many parameters. The server supports a maximum of 2100 parameters.** 

We have a total of 60 forms (and counting). The number of entries is about 7200 and counting.
When we rebuild the UmbracoFormsRecordsIndex index the following error occuring:

```
2021-01-06 16:13:26.498 +01:00 [Error] Exception ("b8f1eb7b").
System.Data.SqlClient.SqlException (0x80131904): The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 216
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryPolicy.cs:line 172
   at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)
   at NPoco.Database.ExecuteDataReader(DbCommand cmd)
   at NPoco.Database.<QueryImp>d__164`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Umbraco.Forms.Core.Data.Storage.RecordFieldStorage.GetAllRecordFields(IEnumerable`1 records, Form form)
   at Umbraco.Forms.Core.Data.Storage.RecordStorage.GetAllRecords(Form form, Boolean includeFields)
   at Umbraco.Forms.Core.Services.RecordService.GetAllRecords(Form form, Boolean includeFields)
   at Umbraco.Forms.Core.Data.RecordIndex.FormsIndexPopulator.PopulateIndexes(IReadOnlyList`1 indexes)
   at Umbraco.Examine.IndexRebuilder.RebuildIndex(String indexName) in D:\a\1\s\src\Umbraco.Examine\IndexRebuilder.cs:line 44
   at Umbraco.Web.Editors.ExamineManagementController.PostRebuildIndex(String indexName) in D:\a\1\s\src\Umbraco.Web\Editors\ExamineManagementController.cs:line 154
ClientConnectionId:dd1cd1f8-d0bb-4a93-affa-30ea86568b89
Error Number:8003,State:1,Class:16
2021-01-06 16:13:26.505 +01:00 [Error] An error occurred rebuilding index System.Data.SqlClient.SqlException (0x80131904): The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 216
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryPolicy.cs:line 172
   at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)
   at NPoco.Database.ExecuteDataReader(DbCommand cmd)
   at NPoco.Database.<QueryImp>d__164`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Umbraco.Forms.Core.Data.Storage.RecordFieldStorage.GetAllRecordFields(IEnumerable`1 records, Form form)
   at Umbraco.Forms.Core.Data.Storage.RecordStorage.GetAllRecords(Form form, Boolean includeFields)
   at Umbraco.Forms.Core.Services.RecordService.GetAllRecords(Form form, Boolean includeFields)
   at Umbraco.Forms.Core.Data.RecordIndex.FormsIndexPopulator.PopulateIndexes(IReadOnlyList`1 indexes)
   at Umbraco.Examine.IndexRebuilder.RebuildIndex(String indexName) in D:\a\1\s\src\Umbraco.Examine\IndexRebuilder.cs:line 44
   at Umbraco.Web.Editors.ExamineManagementController.PostRebuildIndex(String indexName) in D:\a\1\s\src\Umbraco.Web\Editors\ExamineManagementController.cs:line 154
ClientConnectionId:dd1cd1f8-d0bb-4a93-affa-30ea86568b89
Error Number:8003,State:1,Class:16




```
Reproduction
------------
Probably possible to reproduce by creating 60 forms or more and creating a lot of test entries.

### Specifics

Occures in both versions 8.4.1 and 8.6.0
It didn't occurre before, probably the number of forms/fields/records/etc is to much for the used query.

### Expected result

Indexing should handle many forms with many entries.

We use Forms intensively within our Intranet. We would appreciate it if a solution could be found soon.

**Comment by mcl-sz** [comment]
I think it's also causes the problem of this issues with searching in the backoffice: https://github.com/umbraco/Umbraco-CMS/issues/9622

I think for some reason FormService.Get() doesn't return the forms properly. The Umbraco backoffice search searches in Form names and because this fails it raises the error in the backoffice search.

We have this issues in both situations, forms stored in Json files and forms stored in the database.
Currently we use  <setting key="StoreUmbracoFormsInDb" value="True" />

**Comment by nul800sebastiaan** [comment]
Hi there @mcl-sz - That sure is quite a large amount of entries! 😅 Sorry that we didn't foresee this problem. I've made a quick update for this specific error, but we will look into updating other queries that might run into this problem. 

I've made a test build which you can download here: 
[UmbracoForms.Files.8.6.0-alpha.20210107.1.zip](https://github.com/umbraco/Umbraco.Forms.Issues/files/5782711/UmbracoForms.Files.8.6.0-alpha.20210107.1.zip)

This is just version 8.6.0 but with added SQL paging to prevent the error you're seeing now.

All you need to do is replace the files in the bin folder with the new ones from the zip above, and then try to rebuild the Forms index again. I hope that will be enough to help you on your way again, if not, let us know! 

Also, I would appreciate if you could also test umbraco/Umbraco-CMS#9622 after the index rebuild and see if that fixes that error as well, thanks!

**Comment by mcl-sz** [comment]
Hi @nul800sebastiaan  , thank you very much for the patch, but unfortunately it doesn't fix the problem yet. The same error still occures.
Our Forms tables are filled with a lot of personal data. For this reason i can't share our database tables unfortunately.  
If there is any information you need please let me know.

`2021-01-08 09:29:06.289 +01:00 [Error] Exception ("ce7d8fa5").
System.Data.SqlClient.SqlException (0x80131904): The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 216
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryPolicy.cs:line 172
   at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)
   at NPoco.Database.ExecuteDataReader(DbCommand cmd)
   at NPoco.Database.<QueryImp>d__164`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Umbraco.Forms.Core.Data.Storage.RecordFieldStorage.GetAllRecordFields(IEnumerable`1 records, Form form)
   at Umbraco.Forms.Core.Data.Storage.RecordStorage.GetAllRecords(Form form, Boolean includeFields)
   at Umbraco.Forms.Core.Services.RecordService.GetAllRecords(Form form, Boolean includeFields)
   at Umbraco.Forms.Core.Data.RecordIndex.FormsIndexPopulator.PopulateIndexes(IReadOnlyList`1 indexes)
   at Umbraco.Examine.IndexRebuilder.RebuildIndex(String indexName) in D:\a\1\s\src\Umbraco.Examine\IndexRebuilder.cs:line 44
   at Umbraco.Web.Editors.ExamineManagementController.PostRebuildIndex(String indexName) in D:\a\1\s\src\Umbraco.Web\Editors\ExamineManagementController.cs:line 154
ClientConnectionId:63b6a66e-b757-4aff-a844-02a4c571ed50
Error Number:8003,State:1,Class:16
2021-01-08 09:29:06.289 +01:00 [Error] An error occurred rebuilding index System.Data.SqlClient.SqlException (0x80131904): The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 216
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryPolicy.cs:line 172
   at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)
   at NPoco.Database.ExecuteDataReader(DbCommand cmd)
   at NPoco.Database.<QueryImp>d__164`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Umbraco.Forms.Core.Data.Storage.RecordFieldStorage.GetAllRecordFields(IEnumerable`1 records, Form form)
   at Umbraco.Forms.Core.Data.Storage.RecordStorage.GetAllRecords(Form form, Boolean includeFields)
   at Umbraco.Forms.Core.Services.RecordService.GetAllRecords(Form form, Boolean includeFields)
   at Umbraco.Forms.Core.Data.RecordIndex.FormsIndexPopulator.PopulateIndexes(IReadOnlyList`1 indexes)
   at Umbraco.Examine.IndexRebuilder.RebuildIndex(String indexName) in D:\a\1\s\src\Umbraco.Examine\IndexRebuilder.cs:line 44
   at Umbraco.Web.Editors.ExamineManagementController.PostRebuildIndex(String indexName) in D:\a\1\s\src\Umbraco.Web\Editors\ExamineManagementController.cs:line 154
ClientConnectionId:63b6a66e-b757-4aff-a844-02a4c571ed50
Error Number:8003,State:1,Class:16
`

**Comment by nul800sebastiaan** [comment]
That is .. my bad! I forgot to replace a variable! 🤦‍♂️ new build coming up soon, sorry about that!

**Comment by nul800sebastiaan** [comment]
Alright @mcl-sz - here's a new build: 
[UmbracoForms.Files.8.6.0-alpha.20210108.1.zip](https://github.com/umbraco/Umbraco.Forms.Issues/files/5786281/UmbracoForms.Files.8.6.0-alpha.20210108.1.zip)

So what I did was turn the single query into a batched query (1000 params at a time until there are no more params left) but I forgot to update the query to use the batched 1000 params, it was still passing in all the params.. Whoops.

Again, just replace the dlls and give it another try, hopefully it should be good by now!

**Comment by mcl-sz** [comment]
Thanks for the new build @nul800sebastiaan , this fixes our indexing issue!
Unfortunately, this does not solve the problem with searching in the back office 😟 , the Umbraco.Forms.Web.Trees.FormTreeController still returns an error.
Shall i open a new issue for this under this repro (because it looks like an Umbraco Forms issue) or leave it under Umbraco-CMS?

**Comment by nul800sebastiaan** [comment]
@mcl-sz this is very weird, from the info it SEEMS that the caption of a field could be null? But it's a string so seems unlikely.. 

Maybe the field itself is null, which would also be kinda strange. Here's a few new dlls, I've added null checks and added some logging not, if you can look for messages with level `Debug` that start with `Form with Id {formId} has`.. that would be interesting!

[Forms470.zip](https://github.com/umbraco/Umbraco.Forms.Issues/files/5786744/Forms470.zip)

**Comment by mcl-sz** [comment]
@nul800sebastiaan i've copied de DLL's form the Forms470.zip and the backoffice search (and indexrebuilding) works like a charm again!
The log doesn't show any Debug- or Error level messages (only a few regular Information entries).
It this release suiteable for production as well?

**Comment by nul800sebastiaan** [comment]
That's very weird! I only logged if the field was null so it must be that a caption is null. Could I get you to try once more with additional logging on the Caption? I would love to figure out what is causing the null ref error, since it really shouldn't pop up! 😅 

[Forms470.zip](https://github.com/umbraco/Umbraco.Forms.Issues/files/5786851/Forms470.zip)

Sure you can release these to production, but do note that of course they're not on NuGet at the moment so you'll need to make sure your build server uses these custom dlls for now.

**Comment by mcl-sz** [comment]
I stopped the apppool, replaced the dll's from the latest zip and started the apppool again but there are still no (related) entries under "Setting", "Logviewer" or in App_Data\Logs files (created a fresh logfile).

**Comment by nul800sebastiaan** [comment]
Super weird! Well.. I'm just happy that everything seems to be working now! I'll make sure these changes make it to the next patch release, thanks for reporting and many thanks for the help testing as well! 👍

**Comment by mcl-sz** [comment]
Thank you very much for your help and providing a solution, @nul800sebastiaan ! We really appreciate it.

**Comment by afinn-tech** [comment]
System.Data.SqlClient.SqlException (0x80131904): The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 208
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass30_0.<ExecuteDbDataReader>b__0() in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 204
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass33_0`1.<Execute>b__0() in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 222
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryPolicy.cs:line 172
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 219
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 204
   at System.Data.Common.DbCommand.ExecuteReader()
   at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)
   at NPoco.Database.ExecuteDataReader(DbCommand cmd)
   at NPoco.Database.<QueryImp>d__164`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NPoco.Database.Fetch[T](Sql sql)
   at NPoco.Database.Fetch[T](String sql, Object[] args)
   at Umbraco.Forms.Core.Data.Storage.RecordFieldStorage.GetAllRecordFields(IEnumerable`1 records, Form form)
   at Umbraco.Forms.Core.Data.Storage.RecordStorage.GetAllRecords(Form form, Boolean includeFields)
   at Umbraco.Forms.Core.Services.RecordService.GetAllRecords(Form form, Boolean includeFields)
   at Umbraco.Forms.Core.Data.RecordIndex.FormsIndexPopulator.PopulateIndexes(IReadOnlyList`1 indexes)
   at Umbraco.Examine.IndexPopulator.Populate(IIndex[] indexes) in D:\a\1\s\src\Umbraco.Examine\IndexPopulator.cs:line 41
   at Umbraco.Examine.IndexRebuilder.RebuildIndex(String indexName) in D:\a\1\s\src\Umbraco.Examine\IndexRebuilder.cs:line 44
   at Umbraco.Web.Editors.ExamineManagementController.PostRebuildIndex(String indexName) in D:\a\1\s\src\Umbraco.Web\Editors\ExamineManagementController.cs:line 148
ClientConnectionId:7d9fb027-1177-433b-8ddc-a82f530368ea
Error Number:8003,State:1,Class:16
ClientConnectionId before routing:8dd2c5bf-efe3-4a57-b576-7b5c63943071
Routing Destination:b6931f4a0ce5.tr4284.westeurope1-a.worker.database.windows.net,11171


Is there any fix for this ? we get this on Forms index rebuild also , 
Umbraco 8.6.4 
Forms 8.5.5

**Comment by charleslbryant** [comment]
I know this is old, but I just want to confirm that this fix was released. I don't see the issue number 470 mentioned in the changes on https://our.umbraco.com/packages/developer-tools/umbraco-forms/. Don't want to waste time upgrading if it may have been delayed or put in another release. Thanks.

**Comment by AndyButland** [comment]
Hi @charleslbryant - it could be that this fix was missed off the release notes, but I have checked the code comparing the version you are running and the latest, and I can see that a code fix that should resolve this issue has been applied in the interim.

**Comment by charleslbryant** [comment]
Just trying to figure out exactly which version we should target for upgrade. Going to the latest would be ideal, but in case we have issues preventing that, I'd like to know the minimum release version we can upgrade to in order to fix this issue. Thanks for the fast response.

**Comment by AndyButland** [comment]
This issue has been tagged with 8.7.0, so it looks like that would be the minimum you should upgrade to.  I'd recommend getting on the latest if you can though - they are only patch releases after this one - as you'd benefit from a fair few other bug fixes too.

**Comment by charleslbryant** [comment]
Appreciate your help, thanks.
