### ISSUE TITLE
DISTRIBUTED CACHE IS NOT UPDATED. Failed to execute instructions

### ISSUE THREAD

**Issue by mistyn8** [umbraco/Umbraco.Forms.Issues#687]
Umbraco v9.1.2 uForms 9.1.1

Having set up a loadbalanced azure environment for 9.1.2 following https://our.umbraco.com/Documentation/Fundamentals/Setup/server-setup/Load-Balancing/flexible-advanced. Getting errors in the logs re umbracoForms..

```
DISTRIBUTED CACHE IS NOT UPDATED. Failed to execute instructions (6860: '"[{\"RefreshType\":4,\"RefresherId\":\"bd86d2b0-d738-4dbc-be69-87a74b67760c\",\"GuidId\":\"00000000-0000-0000-0000-000000000000\",\"IntId\":0,\"JsonIds\":null,\"JsonIdCount\":1,\"JsonPayload\":\" etc... full log attached below
```
```
Exception
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Umbraco.Forms.Core.Cache.JsonPayloads+WorkflowPayload' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Umbraco.Forms.Core.Cache.WorkflowCacheRefresher.Refresh(String jsonPayload)
   at Umbraco.Cms.Core.Services.Implement.CacheInstructionService.NotifyRefreshers(CacheRefresherCollection cacheRefreshers, IEnumerable`1 instructions, HashSet`1 processed, CancellationToken cancellationToken)
   at Umbraco.Cms.Core.Services.Implement.CacheInstructionService.ProcessDatabaseInstructions(CacheRefresherCollection cacheRefreshers, IReadOnlyCollection`1 instructionBatch, CacheInstruction instruction, HashSet`1 processed, CancellationToken cancellationToken, Int32& lastId)
```
the json from the log seems to be invalid because arrays are wrapped with strings.

eg "JsonPayload":"[{"Workflow: ..... }]" and also show `\"` and `\\"` quoting..
I'm not sure though if this is the logViewer display adding to this.. or if it's the way Forms are being distributed to subscribers?
[DISTRIBUTED CACHE IS NOT UPDATED.txt](https://github.com/umbraco/Umbraco.Forms.Issues/files/7737057/DISTRIBUTED.CACHE.IS.NOT.UPDATED.txt)

Any Ideas?

**Comment by AndyButland** [comment]
Thanks for reporting.  It seems we have a bug with the cache refreshing on V9, in that they are coded to expect a single entity but are receiving a collection.  Looks like a straightforward fix so we'll look to have that out in a patch release in the new year.
