### ISSUE TITLE
Using s3 for media.. /umbraco/backoffice/UmbracoForms/Export/GetExportTypes?formId=guid fails if upload field type used in form

### ISSUE THREAD

**Issue by mistyn8** [umbraco/Umbraco.Forms.Issues#726]
uforms 8.10.2 + Umbraco version 8.15.1

Trying to export a form with upload field used and s3 bucket for media results in error.

we can see that submitted forms are uploading the files at submission (via s3 browser).. just can't export the entries from the back-office admin.
![image](https://user-images.githubusercontent.com/12418214/153576379-2fb8b4f2-d1ac-4b7b-a5e7-27319c5ccad4.png)
![image](https://user-images.githubusercontent.com/12418214/153576434-a0a4606b-98c5-4660-b34d-f3f6340f35f7.png)

`/umbraco/backoffice/UmbracoForms/Export/GetExportTypes?formId=d37c9268-c183-4e2a-968c-6f18437812f0`

```
Possibly unhandled rejection: {"data":{"Message":"An error has occurred.","ExceptionMessage":"The specified key does not exist.","ExceptionType":"System.IO.FileNotFoundException","StackTrace":"   at Umbraco.Storage.S3.BucketFileSystem.Execute[T](Func`2 request)
   at Umbraco.Storage.S3.BucketFileSystem.DirectoryExists(String path)
   at Umbraco.Core.IO.ShadowWrapper.DirectoryExists(String path) in D:\\a\\1\\s\\src\\Umbraco.Core\\IO\\ShadowWrapper.cs:line 140
   at Umbraco.Core.IO.FileSystemWrapper.DirectoryExists(String path) in D:\\a\\1\\s\\src\\Umbraco.Core\\IO\\FileSystemWrapper.cs:line 43
   at Umbraco.Forms.Web.Editors.ExportController.GetExportTypes(Guid formId)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.AuthenticationFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()","InnerException":{"Message":"An error has occurred.","ExceptionMessage":"The specified key does not exist.","ExceptionType":"Amazon.S3.AmazonS3Exception","StackTrace":"   at bool Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/ErrorHandler/HttpErrorResponseExceptionHandler.cs:line 115
   at bool Amazon.Runtime.Internal.ExceptionHandler<T>.Handle(IExecutionContext executionContext, Exception exception) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/ErrorHandler/ExceptionHandler.cs:line 38
   at bool Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/ErrorHandler/ErrorHandler.cs:line 204
   at void Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/ErrorHandler/ErrorHandler.cs:line 78
   at void Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/PipelineHandler.cs:line 55
   at void Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/CallbackHandler.cs:line 45
   at void Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/PipelineHandler.cs:line 55
   at void Amazon.Runtime.Internal.Signer.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/Signer.cs:line 38
   at void Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/PipelineHandler.cs:line 55
   at void Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/EndpointDiscoveryHandler.cs:line 54
   at void Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/PipelineHandler.cs:line 55
   at void Amazon.Runtime.Internal.CredentialsRetriever.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/CredentialsRetriever.cs:line 72
   at void Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/PipelineHandler.cs:line 55
   at void Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/RetryHandler/RetryHandler.cs:line 84
   at void Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/PipelineHandler.cs:line 55
   at void Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/CallbackHandler.cs:line 45
   at void Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/PipelineHandler.cs:line 55
   at void Amazon.S3.Internal.AmazonS3KmsHandler.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Services/S3/Custom/Internal/AmazonS3KmsHandler.cs:line 37
   at void Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/PipelineHandler.cs:line 55
   at void Amazon.Runtime.Internal.EndpointResolver.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/EndpointResolver.cs:line 34
   at void Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/PipelineHandler.cs:line 55
   at void Amazon.S3.Internal.AmazonS3PostMarshallHandler.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Services/S3/Custom/Internal/AmazonS3PostMarshallHandler.cs:line 54
   at void Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/PipelineHandler.cs:line 55
   at void Amazon.Runtime.Internal.Marshaller.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/Marshaller.cs:line 37
   at void Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/PipelineHandler.cs:line 55
   at void Amazon.S3.Internal.AmazonS3PreMarshallHandler.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Services/S3/Custom/Internal/AmazonS3PreMarshallHandler.cs:line 43
   at void Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/PipelineHandler.cs:line 55
   at void Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/CallbackHandler.cs:line 45
   at void Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/PipelineHandler.cs:line 55
   at void Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Services/S3/Custom/Internal/AmazonS3ExceptionHandler.cs:line 48
   at void Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/PipelineHandler.cs:line 55
   at void Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/ErrorCallbackHandler.cs:line 44
   at void Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/PipelineHandler.cs:line 55
   at void Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/MetricsHandler.cs:line 40
   at IResponseContext Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/RuntimePipeline.cs:line 135
   at TResponse Amazon.Runtime.AmazonServiceClient.Invoke<TResponse>(AmazonWebServiceRequest request, InvokeOptionsBase options) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/AmazonServiceClient.cs:line 203
   at ListObjectsResponse Amazon.S3.AmazonS3Client.ListObjects(ListObjectsRequest request) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Services/S3/Generated/_bcl45/AmazonS3Client.cs:line 3591
   at bool Umbraco.Storage.S3.BucketFileSystem.DirectoryExists(string path)+(IAmazonS3 client) => { }
   at T Umbraco.Storage.S3.BucketFileSystem.Execute<T>(Func<IAmazonS3, T> request)","InnerException":{"Message":"An error has occurred.","ExceptionMessage":"The remote server returned an error: (404) Not Found.","ExceptionType":"Amazon.Runtime.Internal.HttpErrorResponseException","StackTrace":"   at IWebResponseData Amazon.Runtime.Internal.HttpRequest.GetResponse() in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/HttpHandler/_bcl/HttpWebRequestFactory.cs:line 174
   at void Amazon.Runtime.Internal.HttpHandler<TRequestContent>.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/HttpHandler/HttpHandler.cs:line 85
   at void Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/PipelineHandler.cs:line 55
   at void Amazon.Runtime.Internal.RedirectHandler.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/RedirectHandler.cs:line 40
   at void Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/PipelineHandler.cs:line 55
   at void Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/Unmarshaller.cs:line 48
   at void Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/PipelineHandler.cs:line 55
   at void Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Services/S3/Custom/Internal/AmazonS3ResponseHandler.cs:line 43
   at void Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/PipelineHandler.cs:line 55
   at void Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext) in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/ErrorHandler/ErrorHandler.cs:line 72","InnerException":{"Message":"An error has occurred.","ExceptionMessage":"The remote server returned an error: (404) Not Found.","ExceptionType":"System.Net.WebException","StackTrace":"   at WebResponse System.Net.HttpWebRequest.GetResponse()
   at IWebResponseData Amazon.Runtime.Internal.HttpRequest.GetResponse() in D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/HttpHandler/_bcl/HttpWebRequestFactory.cs:line 166"}}}},"status":500,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"backoffice/UmbracoForms/Export/GetExportTypes?formId=d37c9268-c183-4e2a-968c-6f18437812f0","headers":{"Accept":"application/json, text/plain, */*","X-Requested-With":"XMLHttpRequest","X-UMB-XSRF-TOKEN":"wTuSK0iA3rnXrfp2QayAj-u0bdWoF0xyJHCeedilArfAz7npdBCBFY5EcfeUaiUwmS5JOBiDiLOEpJYZdXi9_vLfzGZ_-P6EEInkeegkDpiPak6TV_egKibmeqZQjaLXm3LZYnXE0bjN2xwxUwej6A2"}},"statusText":"","xhrStatus":"complete"}
```

**Comment by mistyn8** [comment]
tracked this down to using `bucket="tsd/wc"` with `prefix="media/"` to allow us to have a single bucket with client subfolders.
whilst this works for media and cache support.. once we hit anything that requires checking existence (file/folders) on the s3 bucket errors..
although not sure why uForms is saving the s3 file upload path of the bucket.. as with the default VPP assets are still surfaced on the default `media/` so for instance `sitedomain/media/forms/path-to-asset` would still work where as we were getting 
`/wc/media` introduced  (it's the same when `bucket="tsd"` with `prefix="wc/media/"`) is used. ??
Just noting this here in case anyone else comes across it as a gotach... I'm sure there is a rationale for this. but just means that uForms is surfacing the direct s3 bucket path?

**Comment by Amalie-Wowern** [comment]
We’re doing a bit of cleanup and noticed this issue hasn’t had any activity for over a year, so we’ll close it for now.
 If it’s still relevant, you’re welcome to open a new issue with the latest details.
