### ISSUE TITLE
Issues with saving forms security settings

### ISSUE THREAD

**Issue by Sophiehillebrant** [umbraco/Umbraco.Forms.Issues#757]
### Bug summary

In certain languages, I am not allowed to view or save forms security settings for certain users. This user has Id -1 if that has any impact. The first image is of the UI feedback while tryng to view this users security settings in Swedish. I have not tried many other languages, but it seems I am able to view this users settings in English(USA) at least. Although I am not permitted to save anything (The second image). 
This problem occurs locally. We are running Umbraco version 9.3.1 and UmbracoForms version 9.3.0
Browser: Chrome version 99.0.4844.84

Could it be related to this? 
https://github.com/dotnet/runtime/issues/40922

![image](https://user-images.githubusercontent.com/55388568/161067083-11b2aee3-2a26-40b1-aef5-76687c536c4f.png)

![image](https://user-images.githubusercontent.com/55388568/161067706-5370e628-dcaf-48ab-ba82-f31e0537791e.png)

This is the stack trace of the error that occurs in both instances (viewving and saving):

System.Data.SqlClient.SqlException (0x80131904): Conversion failed when converting the nvarchar value '−1' to data type int.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   at NPoco.Database.Execute(String sql, CommandType commandType, Object[] args)
   at NPoco.Database.Update[T](String sql, Object[] args)
   at Umbraco.Forms.Data.Storage.UserSecurityStorage.UpdateUserSecurity(UserSecurity userSecurity)
   at Umbraco.Forms.Web.Editors.FormSecurityController.SaveAndApplyUserSecurity(FormSecurity security, FormSecurity modelToReturn)
   at Umbraco.Forms.Web.Editors.FormSecurityController.PostSave(FormSecurity security)
   at lambda_method35524(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
ClientConnectionId:e92b9e00-b8a6-4c08-b4d0-e7ae5d540a3e
Error Number:245,State:1,Class:16

###Steps to Reproduce

Run Umbraco version 9.3.1 
Install UmbracoForms version 9.3.0
Create some forms + add a form picker to any document type
Switch backoffice language between swedish and english. The different errors appear in different languages.

### Expected result

To be able to view and save form security settings for the different users regardless of chosen backoffice language.

**Comment by AndyButland** [comment]
Thanks for reporting... and yes, we've run into this one before on the CMS.  We'll get this fixed for the next release.

As you've noted, the issue is the single user that has an id of "-1", which isn't being interpreted as an integer with the Swedish culture.
