### ISSUE TITLE
Migration state error when upgrading Umbraco.Forms from 9.4.2 to 10.1.0

### ISSUE THREAD

**Issue by nickcollinsiom** [umbraco/Umbraco.Forms.Issues#844]
When trying to upgrade Umbraco forms from 9.4.2 to 10.1.0 I receive the following error:

```
An unhandled exception occurred while processing the request.
BootFailedException: Boot failed: Umbraco cannot run. See Umbraco's log file for more details.

-> Umbraco.Cms.Core.Exceptions.BootFailedException: The migration plan does not support migrating from state "236973fb-2461-40d0-8e04-cb74e15481fa".

-> System.InvalidOperationException: The migration plan does not support migrating from state "236973fb-2461-40d0-8e04-cb74e15481fa".
at Umbraco.Cms.Infrastructure.Migrations.MigrationPlan.ThrowOnUnknownInitialState(String state)
at Umbraco.Cms.Infrastructure.Migrations.MigrationPlanExecutor.Execute(MigrationPlan plan, String fromState)
at Umbraco.Cms.Infrastructure.Migrations.Upgrade.Upgrader.Execute(IMigrationPlanExecutor migrationPlanExecutor, ICoreScopeProvider scopeProvider, IKeyValueService keyValueService)
at Umbraco.Cms.Infrastructure.Install.PackageMigrationRunner.RunPackagePlans(IEnumerable`1 plansToRun)
at Umbraco.Cms.Infrastructure.Install.UnattendedUpgrader.HandleAsync(RuntimeUnattendedUpgradeNotification notification, CancellationToken cancellationToken)
```

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

* Upgraded Umbraco from 9.4.3 to 10.1.0
* Upgraded Umbraco.Forms from 9.4.2 to 10.1.0
* Tried to run site, and received the above error.

### Specifics

* Uninstalling Umbraco.Forms resolves the issue but I need it installed so doesn't resolve the issue.

### Steps to reproduce

* Upgrade Umbraco.Cms from 9.4.3 to 10.1.0
* Upgrade Umbraco.Forms from 9.4.2 to 10.1.0
* Go through the upgrade wizard
* Once complete access your site on localhost
* The error should be shown.

### Expected result

* Umbraco.Forms is upgraded to 10.1.0 and usable.

### Actual result

```
An unhandled exception occurred while processing the request.
BootFailedException: Boot failed: Umbraco cannot run. See Umbraco's log file for more details.

-> Umbraco.Cms.Core.Exceptions.BootFailedException: The migration plan does not support migrating from state "236973fb-2461-40d0-8e04-cb74e15481fa".

-> System.InvalidOperationException: The migration plan does not support migrating from state "236973fb-2461-40d0-8e04-cb74e15481fa".
at Umbraco.Cms.Infrastructure.Migrations.MigrationPlan.ThrowOnUnknownInitialState(String state)
at Umbraco.Cms.Infrastructure.Migrations.MigrationPlanExecutor.Execute(MigrationPlan plan, String fromState)
at Umbraco.Cms.Infrastructure.Migrations.Upgrade.Upgrader.Execute(IMigrationPlanExecutor migrationPlanExecutor, ICoreScopeProvider scopeProvider, IKeyValueService keyValueService)
at Umbraco.Cms.Infrastructure.Install.PackageMigrationRunner.RunPackagePlans(IEnumerable`1 plansToRun)
at Umbraco.Cms.Infrastructure.Install.UnattendedUpgrader.HandleAsync(RuntimeUnattendedUpgradeNotification notification, CancellationToken cancellationToken)
```

**Comment by AndyButland** [comment]
Hi - I've just checked that migration ID, and it looks that this was actually the last one of 9.3 rather than 9.4.  To upgrade to Forms 10, it is necessary to be on what was the last minor release of Forms when Umbraco 10 came out, which was 9.3.

So if actually you started from 9.3, then this is expected, and you should first update to at least 9.4.

If you did start from 9.4, then I don't quite understand why you are seeing this, as by installing 9.4 you should have had a migration run to a later state.

If it's reasonably straightforward for you to re-do the migration, but first make 100% sure you are on 9.4 before you start, then I'd suggest to do that.

If that's going to be difficult, let me know and I can likely prepare a database script to get you up to date.  I'm away tomorrow but could do this on Monday for you if it's useful.

**Comment by AndyButland** [comment]
Closing given no further discussion and the outcome looks expected if the migration was from 9.3 rather than 9.4 as originally reported.
