### ISSUE TITLE
10.1.2: Two FormPicker property editors?

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco.Forms.Issues#884]
For some reason (after upgrading to Forms 10.1.2) I have two FormPickers (both with the alias UmbracoForms.FormPicker) available - but only in my local environment.

This breaks Deploy when it tries to update the schema, because the PropertyEditorCollection expects there to be only one.

```
Umbraco.Deploy.Core.Exceptions.ProcessArtifactException: Process pass #0 failed for artifact umb://data-type/11fb3a2bcd47429ca55150d740670190.
 ---> System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at Umbraco.Cms.Core.PropertyEditors.PropertyEditorCollection.get_Item(String alias)
```

I have also upgraded Umbraco and Deploy to latest versions (10.2.1 and 10.1.0), but the error was there before too.

I also have the following packages installed:
```xml
        <PackageReference Include="ExcelNumberFormat" Version="1.1.0" />
        <PackageReference Include="Microsoft.Identity.Web" Version="1.16.0" />
        <PackageReference Include="Our.Umbraco.DocTypeGridEditor" Version="10.0.1" />
        <PackageReference Include="Our.Umbraco.FullTextSearch" Version="3.0.0" />
        <PackageReference Include="Skybrud.Umbraco.GridData" Version="4.0.0-alpha002" />
        <PackageReference Include="Skybrud.Umbraco.Redirects" Version="4.0.3" />
        <PackageReference Include="tooorangey.uEditorNotes" Version="10.0.2" />
        <PackageReference Include="Umbraco.Cloud.StorageProviders.AzureBlob" Version="10.0.0" />
        <PackageReference Include="Umbraco.Cms" Version="10.2.1" />
        <PackageReference Include="Umbraco.Deploy.Cloud" Version="10.1.0" />
        <PackageReference Include="Umbraco.Deploy.Contrib" Version="10.1.0" />
        <PackageReference Include="Umbraco.Deploy.Forms" Version="10.1.0" />
        <PackageReference Include="Umbraco.Forms" Version="10.1.2" />
```

And nothing in my code registers a new propertyeditor with that alias.

**Comment by AndyButland** [comment]
Have you upgraded from Umbraco 9?  If so, it sounds like [this issue](https://github.com/umbraco/Umbraco.Forms.Issues/issues/786).

**Comment by skttl** [comment]
I did - I think it's the same issue, thanks!
