### ISSUE TITLE
Umbraco Forms - Workflow - Save as XML file - Probleem Path from XSLT picker

### ISSUE THREAD

**Issue by ygrave** [umbraco/Umbraco.Forms.Issues#974]
Hi,

I using Umbraco Cloud (V 9.5.4.) and Forms (V9.5.6) and I would like to save the result of a form as a XML file. In the Forms Workflows I have the following definition:
Path: \\home\site\wwwroot\media
Extension: xml
XSLT File: /media/4qzjvol1/sampleumbraco.xslt (selected via the pickup)

When I try to save this XML, I received the following error:
There was a problem trying to save the Record with unique id "c04bfdc3-466c-4d5b-85b6-6405753ee94e" for Form "Employee Value Scan (EVS)" with id "3e244ca2-78b9-43a0-a1ce-d60c99f79168" entry to a file at "\\home\site\wwwroot\media" using the XSLT file "/media/4qzjvol1/sampleumbraco.xslt"

`System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\home\site\wwwroot\media\4qzjvol1\sampleumbraco.xslt'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.Xsl.Xslt.XsltLoader.CreateReader(Uri uri, XmlResolver xmlResolver)
   at System.Xml.Xsl.Xslt.XsltLoader.Load(Compiler compiler, Object stylesheet, XmlResolver xmlResolver)
   at System.Xml.Xsl.Xslt.Compiler.Compile(Object stylesheet, XmlResolver xmlResolver, QilExpression& qil)
   at System.Xml.Xsl.XslCompiledTransform.LoadInternal(Object stylesheet, XsltSettings settings, XmlResolver stylesheetResolver)
   at System.Xml.Xsl.XslCompiledTransform.Load(String stylesheetUri)
   at Umbraco.Forms.Core.Data.Helpers.XsltHelper.TransformXML(String xml, String xsltFile)
   at Umbraco.Forms.Core.Providers.WorkflowTypes.SaveAsFile.Execute(WorkflowExecutionContext context)`

I asked already help to the forum but so far no answer. I hope I will receive help via Github.

Another question about this Umbraco Form option: Is it possible to access this XML file via a public URL? I don't found any information about this in the documentation :-(

In advance thanks.

**Comment by AndyButland** [comment]
Hi @ygrave - am just checking this and it seems we may have a bug where we are looking to retrieve the XSLT file.  So I can try to verify with your setup, would you mind sharing with me the contents of your `sampleumbraco.xslt` file please?

**Comment by ygrave** [comment]
Hi Andy, 
No problem. This is a test file. But like you can see in the error the path to this file looks wrong. If you need more information, please let me know. In advance thanks for your help.
[sampleUmbraco.xslt.txt](https://github.com/umbraco/Umbraco.Forms.Issues/files/10723659/sampleUmbraco.xslt.txt)
I change the extension of the file (github don't accept xslt).

**Comment by AndyButland** [comment]
Thanks, I can see the issue.

I'll mark this to be included in the next patch releases, but, depending on timings, it might just get rolled up into the next minor.

**Comment by ygrave** [comment]
Hi Andy, thanks for your answer. Do you know when can I expected this patch?

**Comment by AndyButland** [comment]
We don't have it scheduled yet but it will be in the next few weeks.

**Comment by ygrave** [comment]
Ok, thanks. I hope this will be fixed soon. I'm a little stuck with my project :-(
