### ISSUE TITLE
AllowEditableFormSubmissions couses YSOD in umbraco 8

### ISSUE THREAD

**Issue by tshlomy** [umbraco/Umbraco.Forms.Issues#98]
We wish to use the feature that allow us to load form with its fields data.

We can achieve that by sending recordId in query-string and define AllowEditableFormSubmissions in umbracoSettings.config file as 'true'

After upgrading to umbraco 8 we are getting YSOD because 'setting' isn't  valid element for umbracoSetting.config the issue is that umbraco forms check for the value of that key - only if it is 'true' it reloads' form values.

here is the stack trace:

System.Configuration.ConfigurationErrorsException
  HResult=0x80131902
  Message=Unrecognized element 'setting'. (...\config\umbracoSettings.config line 4)
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.Configuration.BaseConfigurationRecord.EvaluateOne(String[] keys, SectionInput input, Boolean isTrusted, FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult)
   at System.Configuration.BaseConfigurationRecord.Evaluate(FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult, Boolean getLkg, Boolean getRuntimeObject, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at Umbraco.Core.Configuration.Configs.GetConfig[TConfig](String sectionName) in ...\Umbraco-CMS-release-8.0.0\src\Umbraco.Core\Configuration\Configs.cs:line 86
   at Umbraco.Core.Configuration.Configs.<>c__DisplayClass5_0`1.<Add>b__0() in ...\Umbraco.Core\Configuration\Configs.cs:line 75
   at System.Lazy`1.CreateValue()

**Comment by tshlomy** [comment]
Figure out  we need to use umbracoforms.config
