### ISSUE TITLE
Magic strings parsing empty member properties result in an error in "Send form to URL" workflow

### ISSUE THREAD

**Issue by GertKnuts** [umbraco/Umbraco.Forms.Issues#984]
I am currently experiencing an issue with the "Send form to URL" workflow in Umbraco Forms, where magic strings using member properties, when empty, result in an error. When the form is submitted, the workflow receives an error and does not execute any further. The detailed error information from the logs can be found near the end of this ticket.

**Steps:**
Umbraco: 10.3.2
Forms: 10.1.3

- Create a form
- Add a new workflow of type "Send form to URL"
- In the "Send form to URL" settings, add a valid URL (e.g. Postman mock server) and set the method to "POST"
- In the fields section of the "Send form to URL" settings, add a mapping with alias: "jobtitle", form value: blank and static value "{member.jobtitle}"
- Add the property "jobtitle" to the member object and leave empty when creating a member to test
- Place the form on a secure page and, after login, submit the form from the front-end
- The result is a error in the logs (see below) and no POST is performed

If you execute the same steps but enter a value in the "jobtitle" property of the member, it works as expected and the POST is performed.

**Error result in the Umbraco logs:**

```
System.FormatException: Unrecognized Guid format.
   at System.Guid.GuidResult.SetFailure(Boolean overflow, String failureMessageID)
   at System.Guid.TryParseGuid(ReadOnlySpan`1 guidString, GuidResult& result)
   at System.Guid..ctor(String g)
   at Umbraco.Forms.Core.Providers.WorkflowTypes.PostToUrl.AddFieldMappings(NameValueCollection values, List`1 mappings, Record record)
   at Umbraco.Forms.Core.Providers.WorkflowTypes.PostToUrl.Execute(WorkflowExecutionContext context)
   at Umbraco.Forms.Core.Services.WorkflowExecutionService.ExecuteWorkflow(WorkflowType type, Record record, Form form, FormState state, IWorkflow workflow)
   at Umbraco.Forms.Core.Services.WorkflowExecutionService.ExecuteWorkflows(List`1 workflows, Record record, Form form, FormState state)
```

**Comment by AndyButland** [comment]
Thanks for the clear report @GertKnuts - I can replicate and we have a fix for this, which I'll include in the patch release scheduled for next Tuesday.
